// Code generated by goyacc -o internal/textdic/parser.go -p yy internal/textdic/grammar.y. DO NOT EDIT.

//line internal/textdic/grammar.y:5
package textdic

import __yyfmt__ "fmt"

//line internal/textdic/grammar.y:5

import (
	"fmt"
	"sync"
)

// node is the internal AST element produced by the parser. The exported
// wire type is ParsedWord (see service.go); node stays internal so the
// goyacc grammar surface can change without breaking callers.
type node struct {
	Word       string
	Definition string
	Line       int
}

// parseError is the structured error produced by the lexer and the
// goyacc-generated parser. Line is the 1-based source line at which the
// error was detected.
type parseError struct {
	Line    int
	Message string
}

func (e parseError) Error() string {
	return fmt.Sprintf("%d:%s", e.Line, e.Message)
}

//line internal/textdic/grammar.y:35
type yySymType struct {
	yys   int
	str   string
	line  int
	node  node
	nodes []node
}

const WORD = 57346
const DEFINITION = 57347
const NEWLINE = 57348

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"WORD",
	"DEFINITION",
	"NEWLINE",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line internal/textdic/grammar.y:66

// The goyacc-generated parser uses package-level state (yyParserImpl,
// currentParser), so concurrent calls must be serialised. parserExecMutex
// guards every Parse invocation; nothing else needs additional locking.
var (
	parserExecMutex sync.Mutex
	currentParser   *parserWrapper
)

// parserWrapper bridges the goyacc-generated yyParserImpl with the service
// layer and aggregates lexer + parser errors. Concurrent invocation is
// already serialised by parserExecMutex, so no per-instance lock is needed.
type parserWrapper struct {
	lexer  yyLexer
	nodes  []node
	errors []error
}

// runParse runs the goyacc-generated parser against yylex and returns the
// collected nodes plus any lexer/parser errors.
func runParse(yylex yyLexer) ([]node, []error) {
	parserExecMutex.Lock()
	defer parserExecMutex.Unlock()

	p := &parserWrapper{lexer: yylex}
	currentParser = p
	defer func() { currentParser = nil }()

	yyErrorVerbose = true
	yyNewParser().(*yyParserImpl).Parse(yylex)

	if lx, ok := yylex.(*lexer); ok {
		p.errors = append(p.errors, lx.errors...)
	}
	return p.nodes, p.errors
}

// setNodes is invoked from the start production to publish the final node
// list onto the active parser wrapper.
func (yyrcvr *yyParserImpl) setNodes(nodes []node) {
	if currentParser != nil {
		currentParser.nodes = nodes
	}
}

// Error is the goyacc error callback. tokenLine reflects the line at which
// the offending token began, so we attribute the error there rather than
// to lineNo (which has already advanced past any line terminator the
// parser was reacting to).
func (yyrcvr *yyParserImpl) Error(s string) {
	if currentParser == nil {
		return
	}
	line := 1
	if lx, ok := currentParser.lexer.(*lexer); ok {
		line = lx.tokenLine
		if line < 1 {
			line = lx.lineNo
		}
	}
	currentParser.errors = append(currentParser.errors, parseError{Line: line, Message: s})
}

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 11

var yyAct = [...]int8{
	4, 5, 5, 6, 6, 8, 9, 3, 1, 2,
	7,
}

var yyPact = [...]int16{
	-2, -1000, -3, -1000, -1, 1, -1000, -1000, -1000, -1000,
}

var yyPgo = [...]int8{
	0, 7, 9, 8,
}

var yyR1 = [...]int8{
	0, 3, 2, 2, 2, 1, 1,
}

var yyR2 = [...]int8{
	0, 1, 2, 1, 2, 2, 1,
}

var yyChk = [...]int16{
	-1000, -3, -2, -1, 2, 4, 6, -1, 6, 5,
}

var yyDef = [...]int8{
	0, -2, 1, 3, 0, 0, 6, 2, 4, 5,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/textdic/grammar.y:52
		{
			yyVAL.nodes = yyDollar[1].nodes
			yyrcvr.setNodes(yyDollar[1].nodes)
		}
	case 2:
		yyDollar = yyS[yypt-2 : yypt+1]
//line internal/textdic/grammar.y:56
		{
			if yyDollar[2].node.Word != "" {
				yyVAL.nodes = append(yyDollar[1].nodes, yyDollar[2].node)
			} else {
				yyVAL.nodes = yyDollar[1].nodes
			}
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/textdic/grammar.y:57
		{
			if yyDollar[1].node.Word != "" {
				yyVAL.nodes = []node{yyDollar[1].node}
			} else {
				yyVAL.nodes = []node{}
			}
		}
	case 4:
		yyDollar = yyS[yypt-2 : yypt+1]
//line internal/textdic/grammar.y:58
		{
		}
	case 5:
		yyDollar = yyS[yypt-2 : yypt+1]
//line internal/textdic/grammar.y:62
		{
			yyVAL.node = node{Word: yyDollar[1].str, Definition: yyDollar[2].str, Line: yyDollar[1].line}
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/textdic/grammar.y:63
		{
			yyVAL.node = node{}
		}
	}
	goto yystack /* stack new state and value */
}
