version: "1"

services:
  - type: web
    plan: free
    name: flamingo-backend
    runtime: go
    repo: https://github.com/yasuflatland-lf/flamingo-armond
    rootDir: backend
    buildCommand: |
      go install github.com/pressly/goose/v3/cmd/goose@latest && \
      go mod download && \
      go build -o main .
    startCommand: ./main
    healthCheckPath: /health
    envVars:
      - fromGroup: flamingo-armond


  - type: web
    name: flamingo-frontend
    runtime: static
    repo: https://github.com/yasuflatland-lf/flamingo-armond
    rootDir: frontend
    buildCommand: npm install -g pnpm && pnpm install && pnpm run build
    staticPublishPath: dist
    envVars:
      - fromGroup: flamingo-armond    
    buildFilter:
        paths:
        - src/**/*.tsx
        ignoredPaths:
        - src/**/*.test.*
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin    
