package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"backend/graph/model"
	"backend/internal/auth"
	"backend/internal/domain"
	"backend/internal/gqlerr"
	"backend/internal/usecase"
	"context"
	"fmt"
	"time"
)

// AdminEditUser is the resolver for the adminEditUser field.
func (r *mutationResolver) AdminEditUser(ctx context.Context, id string, input model.AdminEditUserInput) (model.AdminEditUserResult, error) {
	outcome, err := r.AdminUserUC.EditUser(ctx, id, usecase.AdminEditUserInput{
		DisplayName:     input.DisplayName,
		Bio:             input.Bio,
		RoleIDs:         input.RoleIds,
		ExpectedVersion: int64(input.ExpectedVersion),
	})
	if err != nil {
		return nil, gqlerr.FromUsecaseError(ctx, err)
	}
	if outcome.Validation != nil {
		return toInputValidationError(outcome.Validation), nil
	}
	if outcome.CannotRevokeOwnAdmin {
		return model.CannotRevokeOwnAdminRoleError{
			Message: "Cannot revoke your own admin role",
		}, nil
	}
	if outcome.ConcurrentUpdate {
		return model.ConcurrentUpdateError{
			Message: "This user was changed by someone else. Reload and try again.",
		}, nil
	}
	if outcome.User == nil {
		return nil, newNoVariantSetError(ctx, "AdminEditUserOutcome")
	}
	return model.AdminEditUserSuccess{User: toUserModel(outcome.User)}, nil
}

// CreateRole is the resolver for the createRole field.
//
// Returns a union: `model.CreateRoleSuccess` on the happy path, or
// `model.InputValidationError` when the name fails validation (e.g. character
// set, length, duplicate). Validation failures are returned as data; the
// error return is reserved for auth and infrastructure failures.
func (r *mutationResolver) CreateRole(ctx context.Context, name string) (model.CreateRoleResult, error) {
	outcome, err := r.AdminRoleUC.Create(ctx, name)
	if err != nil {
		return nil, gqlerr.FromUsecaseError(ctx, err)
	}
	if outcome.Validation != nil {
		return toInputValidationError(outcome.Validation), nil
	}
	if outcome.Role == nil {
		return nil, newNoVariantSetError(ctx, "CreateRoleOutcome")
	}
	return model.CreateRoleSuccess{Role: toRoleModel(outcome.Role)}, nil
}

// UpdateRole is the resolver for the updateRole field.
//
// Returns a union: `model.UpdateRoleSuccess` on the happy path, or
// `model.CannotModifySystemRoleError` when the target role is a system role
// ("admin", "general"). The system-role case is "errors as data" — the second
// return value is reserved for real errors (auth, validation, internal).
func (r *mutationResolver) UpdateRole(ctx context.Context, id string, name string) (model.UpdateRoleResult, error) {
	outcome, err := r.AdminRoleUC.Update(ctx, id, name)
	if err != nil {
		return nil, gqlerr.FromUsecaseError(ctx, err)
	}
	if outcome.SystemRoleConflict != nil {
		return model.CannotModifySystemRoleError{
			Message:  fmt.Sprintf("cannot rename system role %q", outcome.SystemRoleConflict.Name),
			RoleID:   outcome.SystemRoleConflict.ID,
			RoleName: outcome.SystemRoleConflict.Name,
		}, nil
	}
	if outcome.Role == nil {
		return nil, newNoVariantSetError(ctx, "UpdateRoleOutcome")
	}
	return model.UpdateRoleSuccess{Role: toRoleModel(outcome.Role)}, nil
}

// DeleteRole is the resolver for the deleteRole field.
func (r *mutationResolver) DeleteRole(ctx context.Context, id string) (bool, error) {
	if err := r.AdminRoleUC.Delete(ctx, id); err != nil {
		return false, gqlerr.FromUsecaseError(ctx, err)
	}
	return true, nil
}

// AdminDeleteUser is the resolver for the adminDeleteUser field.
func (r *mutationResolver) AdminDeleteUser(ctx context.Context, id string) (bool, error) {
	if err := r.AdminUserUC.DeleteUser(ctx, id); err != nil {
		return false, gqlerr.FromUsecaseError(ctx, err)
	}
	return true, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, first *int, after *string, last *int, before *string, search *string) (*model.UserConnection, error) {
	uc, err := r.AdminUserUC.List(ctx, first, last, after, before, search)
	if err != nil {
		return nil, gqlerr.FromUsecaseError(ctx, err)
	}
	return toUserConnectionModel(ctx, uc), nil
}

// AdminUser is the resolver for the adminUser field.
func (r *queryResolver) AdminUser(ctx context.Context, id string) (*model.User, error) {
	user, err := r.AdminUserUC.Get(ctx, id)
	if err != nil {
		return nil, gqlerr.FromUsecaseError(ctx, err)
	}
	if user == nil {
		return nil, nil
	}
	return toUserModel(user), nil
}

// Roles is the resolver for the roles field.
func (r *queryResolver) Roles(ctx context.Context) ([]*model.Role, error) {
	roles, err := r.AdminRoleUC.List(ctx)
	if err != nil {
		return nil, gqlerr.FromUsecaseError(ctx, err)
	}
	return toRoleModels(ctx, roles), nil
}

// Role is the resolver for the role field.
func (r *queryResolver) Role(ctx context.Context, id string) (*model.Role, error) {
	role, err := r.AdminRoleUC.Get(ctx, id)
	if err != nil {
		return nil, gqlerr.FromUsecaseError(ctx, err)
	}
	return toRoleModel(role), nil
}

// Roles resolves the user's roles through the per-request RoleByUserID
// DataLoader so the admin users list issues a single batched roles query per
// page instead of one query per row. Authorization mirrors the prior usecase
// path: a caller reads their own roles unconditionally; reading another user's
// roles requires the admin role, computed from the same batch (the caller's
// key joins the request's batch, so there is no extra round trip).
func (r *userResolver) Roles(ctx context.Context, obj *model.User) ([]*model.Role, error) {
	loaders, gqlErr := loadersOrInternal(ctx)
	if gqlErr != nil {
		return nil, gqlErr
	}
	caller := auth.UserFrom(ctx)
	if caller == nil || caller.Sub == "" {
		return nil, gqlerr.Unauthenticated()
	}

	// Register the target-roles load before the admin-status load so both keys
	// share one batch window; the caller's key then joins the page's batch.
	rolesThunk := loaders.RoleByUserID.Load(ctx, obj.ID)

	if caller.Sub != obj.ID {
		callerRoles, err := loaders.RoleByUserID.Load(ctx, caller.Sub)()
		if err != nil {
			return nil, classifyLoaderErr(ctx, err, "resolver: user roles: admin check")
		}
		// Reuse the domain admin-membership predicate rather than a resolver-local
		// role loop, mirroring the adapter in usecase/admin_user.go. Nil entries
		// from the batch loader are skipped defensively before dereferencing.
		callerSet := make(domain.RoleSet, 0, len(callerRoles))
		for _, role := range callerRoles {
			if role != nil {
				callerSet = append(callerSet, *role)
			}
		}
		if !callerSet.ContainsAdmin() {
			return nil, gqlerr.NewForbidden("admin only")
		}
	}

	roles, err := rolesThunk()
	if err != nil {
		return nil, classifyLoaderErr(ctx, err, "resolver: user roles")
	}
	return toRoleModels(ctx, roles), nil
}

// LastSignInAt resolves auth.users.last_sign_in_at via the per-request
// LastSignInByUserID DataLoader (batched, so the admin user list issues one
// auth.users read per page). A nil result means the user has never signed in.
func (r *userResolver) LastSignInAt(ctx context.Context, obj *model.User) (*time.Time, error) {
	loaders, gqlErr := loadersOrInternal(ctx)
	if gqlErr != nil {
		return nil, gqlErr
	}
	t, err := loaders.LastSignInByUserID.Load(ctx, obj.ID)()
	if err != nil {
		return nil, classifyLoaderErr(ctx, err, "resolver: last sign in")
	}
	return t, nil
}
