package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"backend/graph/model"
	"backend/internal/gqlerr"
	"backend/internal/usecase"
	"context"
	"fmt"

	"github.com/rotisserie/eris"
)

// AdminEditUser is the resolver for the adminEditUser field.
func (r *mutationResolver) AdminEditUser(ctx context.Context, id string, input model.AdminEditUserInput) (model.AdminEditUserResult, error) {
	outcome, err := r.AdminUserUC.EditUser(ctx, id, usecase.AdminEditUserInput{
		DisplayName:     input.DisplayName,
		Bio:             input.Bio,
		RoleIDs:         input.RoleIds,
		ExpectedVersion: int64(input.ExpectedVersion),
	})
	if err != nil {
		return nil, gqlerr.FromUsecaseError(ctx, err)
	}
	if outcome.Validation != nil {
		return model.InputValidationError{
			Field:   outcome.Validation.Field,
			Message: outcome.Validation.Message,
		}, nil
	}
	if outcome.CannotRevokeOwnAdmin {
		return model.CannotRevokeOwnAdminRoleError{
			Message: "Cannot revoke your own admin role",
		}, nil
	}
	if outcome.ConcurrentUpdate {
		return model.ConcurrentUpdateError{
			Message: "This user was changed by someone else. Reload and try again.",
		}, nil
	}
	if outcome.User == nil {
		return nil, gqlerr.Internal(ctx,
			eris.New("resolver: AdminEditUserOutcome has no variant set"))
	}
	return model.AdminEditUserSuccess{User: toUserModel(outcome.User)}, nil
}

// CreateRole is the resolver for the createRole field.
//
// Returns a union: `model.CreateRoleSuccess` on the happy path, or
// `model.InputValidationError` when the name fails validation (e.g. character
// set, length, duplicate). Validation failures are returned as data; the
// error return is reserved for auth and infrastructure failures.
func (r *mutationResolver) CreateRole(ctx context.Context, name string) (model.CreateRoleResult, error) {
	outcome, err := r.AdminRoleUC.Create(ctx, name)
	if err != nil {
		return nil, gqlerr.FromUsecaseError(ctx, err)
	}
	if outcome.Validation != nil {
		return model.InputValidationError{
			Field:   outcome.Validation.Field,
			Message: outcome.Validation.Message,
		}, nil
	}
	if outcome.Role == nil {
		return nil, gqlerr.Internal(ctx,
			eris.New("resolver: CreateRoleOutcome has no variant set"))
	}
	return model.CreateRoleSuccess{Role: toRoleModel(outcome.Role)}, nil
}

// UpdateRole is the resolver for the updateRole field.
//
// Returns a union: `model.UpdateRoleSuccess` on the happy path, or
// `model.CannotModifySystemRoleError` when the target role is a system role
// ("admin", "general"). The system-role case is "errors as data" — the second
// return value is reserved for real errors (auth, validation, internal).
func (r *mutationResolver) UpdateRole(ctx context.Context, id string, name string) (model.UpdateRoleResult, error) {
	outcome, err := r.AdminRoleUC.Update(ctx, id, name)
	if err != nil {
		return nil, gqlerr.FromUsecaseError(ctx, err)
	}
	if outcome.SystemRoleConflict != nil {
		return model.CannotModifySystemRoleError{
			Message:  fmt.Sprintf("cannot rename system role %q", outcome.SystemRoleConflict.Name),
			RoleID:   outcome.SystemRoleConflict.ID,
			RoleName: outcome.SystemRoleConflict.Name,
		}, nil
	}
	if outcome.Role == nil {
		return nil, gqlerr.Internal(ctx,
			eris.New("resolver: UpdateRoleOutcome has no variant set"))
	}
	return model.UpdateRoleSuccess{Role: toRoleModel(outcome.Role)}, nil
}

// DeleteRole is the resolver for the deleteRole field.
func (r *mutationResolver) DeleteRole(ctx context.Context, id string) (bool, error) {
	if err := r.AdminRoleUC.Delete(ctx, id); err != nil {
		return false, gqlerr.FromUsecaseError(ctx, err)
	}
	return true, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, first *int, after *string, last *int, before *string, search *string) (*model.UserConnection, error) {
	uc, err := r.AdminUserUC.List(ctx, first, last, after, before, search)
	if err != nil {
		return nil, gqlerr.FromUsecaseError(ctx, err)
	}
	return toUserConnectionModel(ctx, uc), nil
}

// AdminUser is the resolver for the adminUser field.
func (r *queryResolver) AdminUser(ctx context.Context, id string) (*model.User, error) {
	user, err := r.AdminUserUC.Get(ctx, id)
	if err != nil {
		return nil, gqlerr.FromUsecaseError(ctx, err)
	}
	if user == nil {
		return nil, nil
	}
	return toUserModel(user), nil
}

// Roles is the resolver for the roles field.
func (r *queryResolver) Roles(ctx context.Context) ([]*model.Role, error) {
	roles, err := r.AdminRoleUC.List(ctx)
	if err != nil {
		return nil, gqlerr.FromUsecaseError(ctx, err)
	}
	return toRoleModels(ctx, roles), nil
}

// Role is the resolver for the role field.
func (r *queryResolver) Role(ctx context.Context, id string) (*model.Role, error) {
	role, err := r.AdminRoleUC.Get(ctx, id)
	if err != nil {
		return nil, gqlerr.FromUsecaseError(ctx, err)
	}
	return toRoleModel(role), nil
}

// Roles is the resolver for the roles field.
func (r *userResolver) Roles(ctx context.Context, obj *model.User) ([]*model.Role, error) {
	roles, err := r.UserUC.RolesFor(ctx, obj.ID)
	if err != nil {
		return nil, gqlerr.FromUsecaseError(ctx, err)
	}
	return toRoleModels(ctx, roles), nil
}
