package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"backend/graph/generated"
	"backend/graph/model"
	"backend/internal/gqlerr"
	"backend/internal/loader"
	"backend/internal/usecase"
	"context"

	"github.com/rotisserie/eris"
)

// Owner is the resolver for the owner field.
func (r *cardgroupResolver) Owner(ctx context.Context, obj *model.Cardgroup) (*model.User, error) {
	loaders := loader.For(ctx)
	if loaders == nil {
		return nil, gqlerr.Internal(ctx, eris.New("loader: middleware not installed for /query"))
	}
	user, err := loaders.User.Load(ctx, obj.OwnerID)()
	if err != nil {
		return nil, gqlerr.Internal(ctx, err)
	}
	return toUserModel(user), nil
}

// CreateCardgroup is the resolver for the createCardgroup field.
//
// Returns a union: `model.CreateCardgroupSuccess` on the happy path, or
// `model.InputValidationError` when the name fails validation (e.g. empty,
// too long). Validation failures are "errors as data" — the error return is
// reserved for auth and infrastructure failures.
func (r *mutationResolver) CreateCardgroup(ctx context.Context, input model.NewCardgroupInput) (model.CreateCardgroupResult, error) {
	outcome, err := r.CardgroupUC.Create(ctx, usecase.CreateCardgroupInput{Name: input.Name})
	if err != nil {
		return nil, gqlerr.FromUsecaseError(ctx, err)
	}
	if outcome.Validation != nil {
		return model.InputValidationError{
			Field:   outcome.Validation.Field,
			Message: outcome.Validation.Message,
		}, nil
	}
	if outcome.LimitReached != nil {
		return model.CardgroupLimitReachedError{
			Message: "cardgroup limit reached",
			Limit:   outcome.LimitReached.Limit,
			Current: outcome.LimitReached.Current,
		}, nil
	}
	if outcome.Cardgroup == nil {
		return nil, gqlerr.Internal(ctx,
			eris.New("resolver: CreateCardgroupOutcome has no variant set"))
	}
	return model.CreateCardgroupSuccess{Cardgroup: toCardgroupModel(outcome.Cardgroup)}, nil
}

// UpdateCardgroup is the resolver for the updateCardgroup field.
//
// Returns a union: `model.UpdateCardgroupSuccess` on the happy path, or
// `model.InputValidationError` when the name fails validation (e.g. empty,
// too long). Validation failures are "errors as data" — the error return is
// reserved for auth and infrastructure failures.
func (r *mutationResolver) UpdateCardgroup(ctx context.Context, id string, input model.UpdateCardgroupInput) (model.UpdateCardgroupResult, error) {
	outcome, err := r.CardgroupUC.Update(ctx, id, usecase.UpdateCardgroupInput{Name: input.Name})
	if err != nil {
		return nil, gqlerr.FromUsecaseError(ctx, err)
	}
	if outcome.Validation != nil {
		return model.InputValidationError{
			Field:   outcome.Validation.Field,
			Message: outcome.Validation.Message,
		}, nil
	}
	if outcome.Cardgroup == nil {
		return nil, gqlerr.Internal(ctx,
			eris.New("resolver: UpdateCardgroupOutcome has no variant set"))
	}
	return model.UpdateCardgroupSuccess{Cardgroup: toCardgroupModel(outcome.Cardgroup)}, nil
}

// DeleteCardgroup is the resolver for the deleteCardgroup field.
func (r *mutationResolver) DeleteCardgroup(ctx context.Context, id string) (bool, error) {
	if err := r.CardgroupUC.Delete(ctx, id); err != nil {
		return false, gqlerr.FromUsecaseError(ctx, err)
	}
	return true, nil
}

// Cardgroup is the resolver for the cardgroup field.
func (r *queryResolver) Cardgroup(ctx context.Context, id string) (*model.Cardgroup, error) {
	cg, err := r.CardgroupUC.Cardgroup(ctx, id)
	if err != nil {
		return nil, gqlerr.FromUsecaseError(ctx, err)
	}
	return toCardgroupModel(cg), nil
}

// MyCardgroupsConnection is the resolver for the myCardgroupsConnection field.
func (r *queryResolver) MyCardgroupsConnection(ctx context.Context, first *int, after *string, last *int, before *string, search *string, orderBy *model.CardgroupOrderBy, orderDirection *model.SortOrder) (*model.CardgroupConnection, error) {
	out, err := r.CardgroupUC.ListCardgroupsByOwnerConnection(ctx, usecase.CardgroupConnectionInput{
		First:          first,
		Last:           last,
		After:          after,
		Before:         before,
		Search:         search,
		OrderBy:        toUsecaseCardgroupOrderBy(orderBy),
		OrderDirection: toUsecaseSortOrder(orderDirection),
	})
	if err != nil {
		return nil, gqlerr.FromUsecaseError(ctx, err)
	}
	return toCardgroupConnectionModel(ctx, out), nil
}

// Cardgroup returns generated.CardgroupResolver implementation.
func (r *Resolver) Cardgroup() generated.CardgroupResolver { return &cardgroupResolver{r} }

type cardgroupResolver struct{ *Resolver }
