package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.92

import (
	"backend/graph/model"
	"backend/internal/gqlerr"
	"backend/internal/usecase"
	"context"
)

// ImportCards is the resolver for the importCards field.
func (r *mutationResolver) ImportCards(ctx context.Context, input model.ImportCardsInput) (*model.ImportCardsPayload, error) {
	out, err := r.CardImportUC.Import(ctx, usecase.ImportCardsInput{
		CardgroupID: input.CardgroupID,
		Payload:     input.Payload,
	})
	if err != nil {
		return nil, gqlerr.FromUsecaseError(ctx, err)
	}
	return &model.ImportCardsPayload{
		Inserted: int(out.Inserted),
		Updated:  int(out.Updated),
		Errors:   toCardImportErrors(ctx, out.Errors),
	}, nil
}

// ValidateCardImport is the resolver for the validateCardImport field.
func (r *queryResolver) ValidateCardImport(ctx context.Context, input model.ValidateCardImportInput) (*model.CardImportValidationResult, error) {
	out, err := r.CardImportUC.Validate(ctx, input.Payload)
	if err != nil {
		return nil, gqlerr.FromUsecaseError(ctx, err)
	}
	return toCardImportValidationResultModel(ctx, out), nil
}
