package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"backend/graph/generated"
	"backend/graph/model"
	"backend/internal/auth"
	"backend/internal/domain"
	"backend/internal/gqlerr"
	"backend/internal/loader"
	"backend/internal/usecase"
	"context"

	"github.com/rotisserie/eris"
)

// Cardgroup is the resolver for the cardgroup field.
func (r *cardResolver) Cardgroup(ctx context.Context, obj *model.Card) (*model.Cardgroup, error) {
	loaders := loader.For(ctx)
	if loaders == nil {
		return nil, gqlerr.Internal(ctx, eris.New("loader: middleware not installed for /query"))
	}
	cg, err := loaders.Cardgroup.Load(ctx, obj.CardgroupID)()
	if err != nil {
		return nil, gqlerr.Internal(ctx, err)
	}
	return toCardgroupModel(cg), nil
}

// UserCardState is the resolver for the userCardState field.
func (r *cardResolver) UserCardState(ctx context.Context, obj *model.Card) (*model.UserCardState, error) {
	user := auth.UserFrom(ctx)
	if user == nil {
		return nil, gqlerr.Unauthenticated()
	}
	loaders := loader.For(ctx)
	if loaders == nil || loaders.UserCardFSRS == nil {
		return nil, gqlerr.Internal(ctx, eris.New("loader: user card fsrs loader not installed for /query"))
	}
	ucs, err := loaders.UserCardFSRS.Load(ctx, obj.ID)()
	if err != nil {
		return nil, gqlerr.Internal(ctx, err)
	}
	if ucs == nil {
		ucs = domain.NewUserCardFSRSForNewCard(user.Sub, obj.ID, obj.CreatedAt)
	}
	return toModelUserCardState(ucs), nil
}

// CefrLevel is the resolver for the cefrLevel field. It classifies the card's
// front text on read and returns null when no listed word matches.
func (r *cardResolver) CefrLevel(ctx context.Context, obj *model.Card) (*model.CEFRLevel, error) {
	level, ok := r.CEFRUC.Classify(obj.Front)
	if !ok {
		return nil, nil
	}
	m, ok := toCEFRLevelModel(level)
	if !ok {
		// Unreachable in practice: Classify returns ok==true only for
		// A1..C2, all of which toCEFRLevelModel maps. Defensive guard for a
		// future domain level added without a matching mapper arm.
		return nil, nil
	}
	return &m, nil
}

// CreateCard is the resolver for the createCard field.
//
// Returns a union: `model.CreateCardSuccess` on the happy path, or
// `model.CardDuplicateFrontError` when the (cardgroup_id, front) unique index
// is violated. The duplicate case is "errors as data" — the second return
// value is reserved for real errors (auth, validation, internal).
func (r *mutationResolver) CreateCard(ctx context.Context, input model.NewCardInput) (model.CreateCardResult, error) {
	outcome, err := r.CardUC.Create(ctx, usecase.CreateCardInput{
		CardgroupID: input.CardgroupID,
		Front:       input.Front,
		Back:        input.Back,
	})
	if err != nil {
		return nil, gqlerr.FromUsecaseError(ctx, err)
	}
	if outcome.Duplicate != nil {
		return model.CardDuplicateFrontError{
			Message:        "A card with this front already exists in this cardgroup",
			ExistingCardID: outcome.Duplicate.ExistingID,
			ExistingBack:   outcome.Duplicate.ExistingBack,
		}, nil
	}
	if outcome.Card == nil {
		return nil, gqlerr.Internal(ctx,
			eris.New("resolver: CreateCardOutcome has no variant set"))
	}
	return model.CreateCardSuccess{Card: toCardModel(outcome.Card)}, nil
}

// UpdateCard is the resolver for the updateCard field.
//
// Returns a union: `model.UpdateCardSuccess` on the happy path, or
// `model.InputValidationError` when front/back fails validation. Validation
// failures are "errors as data" — the error return is reserved for auth and
// infrastructure failures.
func (r *mutationResolver) UpdateCard(ctx context.Context, id string, input model.UpdateCardInput) (model.UpdateCardResult, error) {
	outcome, err := r.CardUC.Update(ctx, id, usecase.UpdateCardInput{
		Front: input.Front,
		Back:  input.Back,
	})
	if err != nil {
		return nil, gqlerr.FromUsecaseError(ctx, err)
	}
	if outcome.Validation != nil {
		return model.InputValidationError{
			Field:   outcome.Validation.Field,
			Message: outcome.Validation.Message,
		}, nil
	}
	if outcome.Card == nil {
		return nil, gqlerr.Internal(ctx,
			eris.New("resolver: UpdateCardOutcome has no variant set"))
	}
	return model.UpdateCardSuccess{Card: toCardModel(outcome.Card)}, nil
}

// DeleteCard is the resolver for the deleteCard field.
func (r *mutationResolver) DeleteCard(ctx context.Context, id string) (bool, error) {
	if err := r.CardUC.Delete(ctx, id); err != nil {
		return false, gqlerr.FromUsecaseError(ctx, err)
	}
	return true, nil
}

// DeleteCards is the resolver for the deleteCards field.
func (r *mutationResolver) DeleteCards(ctx context.Context, ids []string) (int, error) {
	n, err := r.CardUC.BulkDelete(ctx, ids)
	if err != nil {
		return 0, gqlerr.FromUsecaseError(ctx, err)
	}
	return int(n), nil
}

// Card is the resolver for the card field.
func (r *queryResolver) Card(ctx context.Context, id string) (*model.Card, error) {
	card, err := r.CardUC.Card(ctx, id)
	if err != nil {
		return nil, gqlerr.FromUsecaseError(ctx, err)
	}
	return toCardModel(card), nil
}

// LearnNextDueCards is the resolver for the learnNextDueCards field.
func (r *queryResolver) LearnNextDueCards(ctx context.Context, cardgroupID string, limit *int) ([]*model.Card, error) {
	cards, err := r.LearnUC.NextDueCards(ctx, cardgroupID, limit)
	if err != nil {
		return nil, gqlerr.FromUsecaseError(ctx, err)
	}
	return toCardModels(ctx, cards), nil
}

// CardsByCardgroupConnection is the resolver for the cardsByCardgroupConnection field.
func (r *queryResolver) CardsByCardgroupConnection(ctx context.Context, cardgroupID string, first *int, after *string, last *int, before *string, search *string, orderBy *model.CardOrderBy, orderDirection *model.SortOrder) (*model.CardConnection, error) {
	out, err := r.CardUC.ListCardsByCardgroupConnection(ctx, usecase.CardConnectionInput{
		CardgroupID:    cardgroupID,
		First:          first,
		Last:           last,
		After:          after,
		Before:         before,
		Search:         search,
		OrderBy:        toUsecaseCardOrderBy(orderBy),
		OrderDirection: toUsecaseSortOrder(orderDirection),
	})
	if err != nil {
		return nil, gqlerr.FromUsecaseError(ctx, err)
	}
	return toCardConnectionModel(ctx, out), nil
}

// Card returns generated.CardResolver implementation.
func (r *Resolver) Card() generated.CardResolver { return &cardResolver{r} }

type cardResolver struct{ *Resolver }
