package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"backend/graph/model"
	"backend/internal/gqlerr"
	"backend/internal/usecase"
	"context"
)

// UpsertDictionary is the resolver for the upsertDictionary field.
func (r *mutationResolver) UpsertDictionary(ctx context.Context, input model.UpsertDictionaryInput) (*model.UpsertDictionaryPayload, error) {
	out, err := r.DictionaryUC.Upsert(ctx, usecase.UpsertDictionaryInput{
		CardgroupID: input.CardgroupID,
		Payload:     input.Payload,
	})
	if err != nil {
		return nil, gqlerr.FromUsecaseError(ctx, err)
	}
	return &model.UpsertDictionaryPayload{
		Inserted: int(out.Inserted),
		Updated:  int(out.Updated),
		Errors:   toDictionaryValidationErrorsFromUpsert(ctx, out.Errors),
	}, nil
}

// ValidateDictionary is the resolver for the validateDictionary field.
func (r *queryResolver) ValidateDictionary(ctx context.Context, input model.ValidateDictionaryInput) (*model.DictionaryValidationResult, error) {
	out, err := r.DictionaryUC.Validate(ctx, input.Payload)
	if err != nil {
		return nil, gqlerr.FromUsecaseError(ctx, err)
	}
	return toDictionaryValidationResultModel(ctx, out), nil
}
