package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"backend/graph/model"
	"backend/internal/gqlerr"
	"backend/internal/loader"
	"backend/internal/repository"
	"context"
	"errors"

	"github.com/rotisserie/eris"
)

// SetLastViewedCardgroup is the resolver for the setLastViewedCardgroup field.
//
// Returns a union: `model.SetLastViewedCardgroupSuccess` on the happy path, or
// `model.InputValidationError` when cardgroupId fails validation (e.g. the
// cardgroup no longer exists or is not owned by the caller). Validation
// failures are "errors as data" — the error return is reserved for auth and
// infrastructure failures.
func (r *mutationResolver) SetLastViewedCardgroup(ctx context.Context, cardgroupID string) (model.SetLastViewedCardgroupResult, error) {
	outcome, err := r.LastViewedCardgroupUC.Set(ctx, cardgroupID)
	if err != nil {
		return nil, gqlerr.FromUsecaseError(ctx, err)
	}
	if outcome.Validation != nil {
		return model.InputValidationError{
			Field:   outcome.Validation.Field,
			Message: outcome.Validation.Message,
		}, nil
	}
	if outcome.User == nil {
		return nil, gqlerr.Internal(ctx,
			eris.New("resolver: SetLastViewedCardgroupOutcome has no variant set"))
	}
	return model.SetLastViewedCardgroupSuccess{User: toUserModel(outcome.User)}, nil
}

// LastViewedCardgroup hydrates via two DataLoaders: UserPreferenceLoader
// (batched by user_id) then CardgroupLoader (batched by cardgroup_id),
// preventing N+1 queries across both layers.
func (r *userResolver) LastViewedCardgroup(ctx context.Context, obj *model.User) (*model.Cardgroup, error) {
	loaders := loader.For(ctx)
	if loaders == nil {
		return nil, gqlerr.Internal(ctx, eris.New("loader: middleware not installed for /query"))
	}

	pref, err := loaders.UserPreference.Load(ctx, obj.ID)()
	if err != nil {
		if errors.Is(err, context.Canceled) || errors.Is(err, context.DeadlineExceeded) {
			return nil, gqlerr.Cancelled(ctx, err)
		}
		return nil, gqlerr.Internal(ctx, eris.Wrap(err, "resolver: user preference"))
	}
	if pref == nil || pref.LastViewedCardgroupID == nil {
		return nil, nil
	}

	cg, err := loaders.Cardgroup.Load(ctx, *pref.LastViewedCardgroupID)()
	if err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return nil, nil
		}
		if errors.Is(err, context.Canceled) || errors.Is(err, context.DeadlineExceeded) {
			return nil, gqlerr.Cancelled(ctx, err)
		}
		return nil, gqlerr.Internal(ctx, eris.Wrap(err, "resolver: cardgroup"))
	}
	return toCardgroupModel(cg), nil
}
