package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.92

import (
	"backend/graph/model"
	"backend/internal/gqlerr"
	"backend/internal/loader"
	"context"
	"errors"
)

// SetLastViewedCardgroup is the resolver for the setLastViewedCardgroup field.
//
// Returns a union: `model.SetLastViewedCardgroupSuccess` on the happy path, or
// `model.InputValidationError` when cardgroupId fails validation (e.g. the
// cardgroup no longer exists or is not owned by the caller). Validation
// failures are "errors as data" — the error return is reserved for auth and
// infrastructure failures.
func (r *mutationResolver) SetLastViewedCardgroup(ctx context.Context, cardgroupID string) (model.SetLastViewedCardgroupResult, error) {
	outcome, err := r.LastViewedCardgroupUC.Set(ctx, cardgroupID)
	if err != nil {
		return nil, gqlerr.FromUsecaseError(ctx, err)
	}
	if outcome.Validation != nil {
		return toInputValidationError(outcome.Validation), nil
	}
	if outcome.User == nil {
		return nil, noVariantSet(ctx, "SetLastViewedCardgroupOutcome")
	}
	return model.SetLastViewedCardgroupSuccess{User: toUserModel(outcome.User)}, nil
}

// LastViewedCardgroup hydrates via two DataLoaders: UserPreferenceLoader
// (batched by user_id) then CardgroupLoader (batched by cardgroup_id),
// preventing N+1 queries across both layers.
func (r *userResolver) LastViewedCardgroup(ctx context.Context, obj *model.User) (*model.Cardgroup, error) {
	loaders, gqlErr := loadersOrInternal(ctx)
	if gqlErr != nil {
		return nil, gqlErr
	}

	pref, err := loaders.UserPreference.Load(ctx, obj.ID)()
	if err != nil {
		return nil, classifyLoaderErr(ctx, err, "resolver: user preference")
	}
	if pref == nil || pref.LastViewedCardgroupID == nil {
		return nil, nil
	}

	cg, err := loaders.Cardgroup.Load(ctx, *pref.LastViewedCardgroupID)()
	if err != nil {
		if errors.Is(err, loader.ErrNotFound) {
			return nil, nil
		}
		return nil, classifyLoaderErr(ctx, err, "resolver: cardgroup")
	}
	return toCardgroupModel(cg), nil
}
