package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"backend/graph/model"
	"backend/internal/domain"
	"backend/internal/gqlerr"
	"context"

	"github.com/rotisserie/eris"
)

// UpdateLearnDisplayMode is the resolver for the updateLearnDisplayMode field.
func (r *mutationResolver) UpdateLearnDisplayMode(ctx context.Context, mode model.LearnDisplayMode) (*model.User, error) {
	domainMode, err := fromLearnDisplayModeModel(mode)
	if err != nil {
		// Defense-in-depth: the GraphQL layer rejects unknown enum values before
		// the resolver runs, so this branch is only reachable via a schema mismatch
		// or a broken client that bypasses enum validation. INTERNAL is correct here
		// rather than BAD_USER_INPUT because the fault is structural, not a
		// correctable user mistake.
		return nil, gqlerr.Internal(ctx, eris.Wrap(err, "resolver: update learn display mode"))
	}
	user, err := r.UpdateLearnDisplayModeUC.Set(ctx, domainMode)
	if err != nil {
		return nil, gqlerr.FromUsecaseError(ctx, err)
	}
	return toUserModel(user), nil
}

// LearnDisplayMode is the resolver for the learnDisplayMode field.
func (r *userResolver) LearnDisplayMode(ctx context.Context, obj *model.User) (model.LearnDisplayMode, error) {
	loaders, gqlErr := loadersOrInternal(ctx)
	if gqlErr != nil {
		return "", gqlErr
	}

	pref, err := loaders.UserPreference.Load(ctx, obj.ID)()
	if err != nil {
		return "", classifyLoaderErr(ctx, err, "resolver: user preference")
	}
	mode := domain.DefaultLearnDisplayMode
	if pref != nil {
		mode = pref.LearnDisplayMode
	}
	return toLearnDisplayModeModel(mode), nil
}
