package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"backend/graph/model"
	"backend/internal/gqlerr"
	"backend/internal/usecase"
	"context"

	"github.com/rotisserie/eris"
)

// ImportMasterCardgroup is the resolver for the importMasterCardgroup field.
//
// Returns a union: model.ImportMasterCardgroupSuccess on the happy path, or
// model.MasterNotFoundError when the master id is unknown or not published
// (draft existence is never leaked). The not-found case is "errors as data";
// the error return is reserved for auth and infrastructure failures.
func (r *mutationResolver) ImportMasterCardgroup(ctx context.Context, masterCardgroupID string) (model.ImportMasterCardgroupResult, error) {
	outcome, err := r.MasterCatalogUC.ImportMaster(ctx, masterCardgroupID)
	if err != nil {
		return nil, gqlerr.FromUsecaseError(ctx, err)
	}
	if outcome.NotFound {
		return model.MasterNotFoundError{
			Message: "Master cardgroup not found",
		}, nil
	}
	if outcome.Cardgroup == nil {
		return nil, gqlerr.Internal(ctx,
			eris.New("resolver: ImportMasterOutcome has no variant set"))
	}
	return model.ImportMasterCardgroupSuccess{
		Cardgroup: toCardgroupModel(outcome.Cardgroup),
	}, nil
}

// MasterCatalog is the resolver for the masterCatalog field.
func (r *queryResolver) MasterCatalog(ctx context.Context, first *int, after *string, last *int, before *string, search *string, orderBy *model.MasterCatalogOrderBy, orderDirection *model.SortOrder) (*model.MasterCatalogConnection, error) {
	out, err := r.MasterCatalogUC.ListPublishedConnection(ctx, usecase.MasterCatalogConnectionInput{
		First:          first,
		Last:           last,
		After:          after,
		Before:         before,
		Search:         search,
		OrderBy:        toUsecaseMasterCatalogOrderBy(orderBy),
		OrderDirection: toUsecaseSortOrder(orderDirection),
	})
	if err != nil {
		return nil, gqlerr.FromUsecaseError(ctx, err)
	}
	return toMasterCatalogConnectionModel(ctx, out), nil
}
