package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"backend/graph/model"
	"backend/internal/gqlerr"
	"backend/internal/usecase"
	"context"

	"github.com/rotisserie/eris"
)

// AdminCreateMasterCardgroup is the resolver for the adminCreateMasterCardgroup field.
//
// Returns a union: `model.CreateMasterCardgroupSuccess` on the happy path, or
// `model.InputValidationError` when the name fails validation (e.g. empty, too
// long). Validation failures are "errors as data" — the error return is reserved
// for auth and infrastructure failures.
func (r *mutationResolver) AdminCreateMasterCardgroup(ctx context.Context, input model.CreateMasterCardgroupInput) (model.CreateMasterCardgroupResult, error) {
	out, err := r.MasterCatalogUC.CreateMaster(ctx, usecase.CreateMasterInput{
		Name:             input.Name,
		Description:      input.Description,
		IsDefaultStarter: input.IsDefaultStarter,
		SortOrder:        input.SortOrder,
	})
	if err != nil {
		return nil, gqlerr.FromUsecaseError(ctx, err)
	}
	if out.Validation != nil {
		return toInputValidationError(out.Validation), nil
	}
	if out.Master == nil {
		return nil, noVariantSet(ctx, "CreateMasterOutcome")
	}
	return model.CreateMasterCardgroupSuccess{Master: toMasterCardgroupModelFromParts(out.Master, cardCountResolvedElsewhere)}, nil
}

// AdminUpdateMasterCardgroup is the resolver for the adminUpdateMasterCardgroup field.
//
// Returns a union: `model.UpdateMasterCardgroupSuccess` on the happy path, or
// `model.InputValidationError` when any field fails validation (e.g. empty or
// too-long name). Validation failures are "errors as data" — the error return is
// reserved for auth and infrastructure failures.
func (r *mutationResolver) AdminUpdateMasterCardgroup(ctx context.Context, id string, input model.UpdateMasterCardgroupInput) (model.UpdateMasterCardgroupResult, error) {
	out, err := r.MasterCatalogUC.UpdateMaster(ctx, id, usecase.UpdateMasterInput{
		Name:             input.Name,
		Description:      input.Description,
		IsDefaultStarter: input.IsDefaultStarter,
		SortOrder:        input.SortOrder,
	})
	if err != nil {
		return nil, gqlerr.FromUsecaseError(ctx, err)
	}
	if out.Validation != nil {
		return toInputValidationError(out.Validation), nil
	}
	if out.Master == nil {
		return nil, noVariantSet(ctx, "UpdateMasterOutcome")
	}
	return model.UpdateMasterCardgroupSuccess{Master: toMasterCardgroupModelFromParts(out.Master, int(out.CardCount))}, nil
}

// AdminPublishMasterCardgroup is the resolver for the adminPublishMasterCardgroup field.
//
// Returns a union: `model.PublishMasterCardgroupSuccess` on the happy path, or
// `model.MasterCardgroupEmptyError` when the deck has zero cards and cannot be
// published. The empty-deck case is "errors as data" — the error return is
// reserved for auth and infrastructure failures.
func (r *mutationResolver) AdminPublishMasterCardgroup(ctx context.Context, id string) (model.PublishMasterCardgroupResult, error) {
	out, err := r.MasterCatalogUC.PublishMaster(ctx, id)
	if err != nil {
		return nil, gqlerr.FromUsecaseError(ctx, err)
	}
	if out.EmptyMaster {
		return model.MasterCardgroupEmptyError{Message: "master cardgroup has no cards and cannot be published"}, nil
	}
	if out.Master == nil {
		return nil, noVariantSet(ctx, "PublishMasterOutcome")
	}
	return model.PublishMasterCardgroupSuccess{Master: toMasterCardgroupModelFromParts(out.Master, int(out.CardCount))}, nil
}

// AdminUnpublishMasterCardgroup is the resolver for the adminUnpublishMasterCardgroup field.
func (r *mutationResolver) AdminUnpublishMasterCardgroup(ctx context.Context, id string) (*model.MasterCardgroup, error) {
	res, err := r.MasterCatalogUC.UnpublishMaster(ctx, id)
	if err != nil {
		return nil, gqlerr.FromUsecaseError(ctx, err)
	}
	if res == nil || res.Master == nil {
		return nil, gqlerr.Internal(ctx, eris.New("resolver: UnpublishMaster returned no master"))
	}
	return toMasterCardgroupModelFromParts(res.Master, int(res.CardCount)), nil
}

// AdminDeleteMasterCardgroup is the resolver for the adminDeleteMasterCardgroup field.
func (r *mutationResolver) AdminDeleteMasterCardgroup(ctx context.Context, id string) (bool, error) {
	if err := r.MasterCatalogUC.DeleteMaster(ctx, id); err != nil {
		return false, gqlerr.FromUsecaseError(ctx, err)
	}
	return true, nil
}

// ImportMasterCardgroup is the resolver for the importMasterCardgroup field.
//
// Returns a union: model.ImportMasterCardgroupSuccess on the happy path, or
// model.MasterNotFoundError when the master id is unknown or not published
// (draft existence is never leaked). The not-found case is "errors as data";
// the error return is reserved for auth and infrastructure failures.
func (r *mutationResolver) ImportMasterCardgroup(ctx context.Context, masterCardgroupID string) (model.ImportMasterCardgroupResult, error) {
	outcome, err := r.MasterCatalogUC.ImportMaster(ctx, masterCardgroupID)
	if err != nil {
		return nil, gqlerr.FromUsecaseError(ctx, err)
	}
	if outcome.NotFound {
		return model.MasterNotFoundError{
			Message: "Master cardgroup not found",
		}, nil
	}
	if outcome.Cardgroup == nil {
		return nil, noVariantSet(ctx, "ImportMasterOutcome")
	}
	return model.ImportMasterCardgroupSuccess{
		Cardgroup: toCardgroupModel(outcome.Cardgroup),
	}, nil
}

// SeedDefaultStarterCardgroups is the resolver for the seedDefaultStarterCardgroups field.
// Copies the published default-starter master decks into the caller's cardgroups
// (idempotent). Backs the onboarding "start with the default decks" path.
func (r *mutationResolver) SeedDefaultStarterCardgroups(ctx context.Context) (*model.SeedDefaultStartersPayload, error) {
	cgs, err := r.MasterCatalogUC.SeedDefaultStarters(ctx)
	if err != nil {
		return nil, gqlerr.FromUsecaseError(ctx, err)
	}
	out := make([]*model.Cardgroup, 0, len(cgs))
	for _, cg := range cgs {
		out = append(out, toCardgroupModel(cg))
	}
	return &model.SeedDefaultStartersPayload{Cardgroups: out}, nil
}

// MergeMasterCardgroup is the resolver for the mergeMasterCardgroup field.
//
// Returns a union: model.MergeMasterCardgroupSuccess on the happy path, or
// model.MasterNotFoundError when the master id is unknown or not published.
// Destination cardgroup auth failures (unknown → BAD_USER_INPUT, foreign →
// UNAUTHENTICATED) travel the error return via FromUsecaseError.
func (r *mutationResolver) MergeMasterCardgroup(ctx context.Context, input model.MergeMasterCardgroupInput) (model.MergeMasterCardgroupResult, error) {
	outcome, err := r.MasterCatalogUC.MergeMaster(ctx, input.MasterCardgroupID, input.CardgroupID)
	if err != nil {
		return nil, gqlerr.FromUsecaseError(ctx, err)
	}
	if outcome.NotFound {
		return model.MasterNotFoundError{Message: "Master cardgroup not found"}, nil
	}
	if outcome.Cardgroup == nil {
		return nil, noVariantSet(ctx, "MergeMasterOutcome")
	}
	return model.MergeMasterCardgroupSuccess{
		Cardgroup:    toCardgroupModel(outcome.Cardgroup),
		AddedCount:   int(outcome.Added),
		UpdatedCount: int(outcome.Updated),
	}, nil
}

// MasterCatalog is the resolver for the masterCatalog field.
func (r *queryResolver) MasterCatalog(ctx context.Context, first *int, after *string, last *int, before *string, search *string, orderBy *model.MasterCatalogOrderBy, orderDirection *model.SortOrder) (*model.MasterCatalogConnection, error) {
	out, err := r.MasterCatalogUC.ListPublishedConnection(ctx, usecase.MasterCatalogConnectionInput{
		First:          first,
		Last:           last,
		After:          after,
		Before:         before,
		Search:         search,
		OrderBy:        toUsecaseOrderBy[model.MasterCatalogOrderBy, usecase.MasterCatalogOrderBy](orderBy),
		OrderDirection: toUsecaseOrderBy[model.SortOrder, usecase.SortOrder](orderDirection),
	})
	if err != nil {
		return nil, gqlerr.FromUsecaseError(ctx, err)
	}
	return toMasterCatalogConnectionModel(ctx, out), nil
}

// AdminMasters is the resolver for the adminMasters field.
func (r *queryResolver) AdminMasters(ctx context.Context, first *int, after *string, last *int, before *string, search *string, orderBy *model.MasterCatalogOrderBy, orderDirection *model.SortOrder) (*model.MasterCatalogConnection, error) {
	out, err := r.MasterCatalogUC.ListAdminConnection(ctx, usecase.MasterCatalogConnectionInput{
		First:          first,
		Last:           last,
		After:          after,
		Before:         before,
		Search:         search,
		OrderBy:        toUsecaseOrderBy[model.MasterCatalogOrderBy, usecase.MasterCatalogOrderBy](orderBy),
		OrderDirection: toUsecaseOrderBy[model.SortOrder, usecase.SortOrder](orderDirection),
	})
	if err != nil {
		return nil, gqlerr.FromUsecaseError(ctx, err)
	}
	return toMasterCatalogConnectionModel(ctx, out), nil
}

// MergeMasterCardgroupPreview is the resolver for the mergeMasterCardgroupPreview field.
//
// Read-only dry run of mergeMasterCardgroup. Returns a union:
// model.MergeMasterCardgroupPreview on the happy path, or model.MasterNotFoundError
// when the master id is unknown or not published. Destination cardgroup auth failures
// (unknown → BAD_USER_INPUT, foreign → UNAUTHENTICATED) travel the error return via
// FromUsecaseError.
func (r *queryResolver) MergeMasterCardgroupPreview(ctx context.Context, input model.MergeMasterCardgroupInput) (model.MergeMasterCardgroupPreviewResult, error) {
	outcome, err := r.MasterCatalogUC.PreviewMergeMaster(ctx, input.MasterCardgroupID, input.CardgroupID)
	if err != nil {
		return nil, gqlerr.FromUsecaseError(ctx, err)
	}
	if outcome.NotFound {
		return model.MasterNotFoundError{Message: "Master cardgroup not found"}, nil
	}
	return model.MergeMasterCardgroupPreview{
		AddedCount:   int(outcome.Added),
		UpdatedCount: int(outcome.Updated),
	}, nil
}
