package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.91

import (
	"backend/graph/model"
	"context"
	"fmt"
)

// AdminMaster is the resolver for the adminMaster field.
func (r *queryResolver) AdminMaster(ctx context.Context, id string) (*model.MasterCardgroup, error) {
	panic(fmt.Errorf("not implemented: AdminMaster - adminMaster"))
}

// AdminMasterCardsConnection is the resolver for the adminMasterCardsConnection field.
func (r *queryResolver) AdminMasterCardsConnection(ctx context.Context, masterCardgroupID string, first *int, after *string, last *int, before *string, search *string, orderBy *model.MasterCardOrderBy, orderDirection *model.SortOrder) (*model.MasterCardConnection, error) {
	panic(fmt.Errorf("not implemented: AdminMasterCardsConnection - adminMasterCardsConnection"))
}
