package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"backend/graph/model"
	"backend/internal/domain"
	"backend/internal/gqlerr"
	"context"
)

// UpdateNewCardRatio is the resolver for the updateNewCardRatio field.
func (r *mutationResolver) UpdateNewCardRatio(ctx context.Context, numerator int, denominator int) (*model.User, error) {
	ratio, err := domain.ParseNewCardRatio(numerator, denominator)
	if err != nil {
		// A ratio outside 1 <= numerator < denominator <= 100 (after reduction) is
		// a correctable client mistake, so surface it as BAD_USER_INPUT rather than
		// INTERNAL. The VO's error carries the precise reason; the wire message stays
		// generic to avoid leaking internal bounds phrasing.
		//
		// Attribute extensions.field to the argument ParseNewCardRatio faulted on,
		// mirroring its check order: a non-positive denominator (and a reduced
		// denominator above NewCardRatioDenMax) map to "denominator"; a numerator
		// outside (0, denominator) maps to "numerator".
		field := "denominator"
		switch {
		case denominator <= 0:
			field = "denominator"
		case numerator <= 0 || numerator >= denominator:
			field = "numerator"
		default: // reduced denominator exceeds NewCardRatioDenMax
			field = "denominator"
		}
		return nil, gqlerr.BadUserInput(field, "invalid new-card ratio")
	}
	user, err := r.UpdateNewCardRatioUC.Set(ctx, ratio)
	if err != nil {
		return nil, gqlerr.FromUsecaseError(ctx, err)
	}
	return toUserModel(user), nil
}

// NewCardRatio is the resolver for the newCardRatio field.
func (r *userResolver) NewCardRatio(ctx context.Context, obj *model.User) (*model.NewCardRatio, error) {
	loaders, gqlErr := loadersOrInternal(ctx)
	if gqlErr != nil {
		return nil, gqlErr
	}

	pref, err := loaders.UserPreference.Load(ctx, obj.ID)()
	if err != nil {
		return nil, classifyLoaderErr(ctx, err, "resolver: user preference")
	}
	ratio := domain.DefaultNewCardRatio
	if pref != nil {
		ratio = pref.EffectiveNewCardRatio()
	}
	return toNewCardRatioModel(ratio), nil
}
