package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"backend/graph/model"
	"backend/internal/domain"
	"backend/internal/gqlerr"
	"context"
)

// UpdateNewCardRatio is the resolver for the updateNewCardRatio field.
func (r *mutationResolver) UpdateNewCardRatio(ctx context.Context, numerator int, denominator int) (*model.User, error) {
	user, err := r.UpdateNewCardRatioUC.Set(ctx, numerator, denominator)
	if err != nil {
		return nil, gqlerr.FromUsecaseError(ctx, err)
	}
	return toUserModel(user), nil
}

// NewCardRatio is the resolver for the newCardRatio field.
func (r *userResolver) NewCardRatio(ctx context.Context, obj *model.User) (*model.NewCardRatio, error) {
	loaders, gqlErr := loadersOrInternal(ctx)
	if gqlErr != nil {
		return nil, gqlErr
	}

	pref, err := loaders.UserPreference.Load(ctx, obj.ID)()
	if err != nil {
		return nil, classifyLoaderErr(ctx, err, "resolver: user preference")
	}
	ratio := domain.DefaultNewCardRatio
	if pref != nil && !pref.NewCardRatio.IsZero() {
		ratio = pref.NewCardRatio
	}
	return toNewCardRatioModel(ratio), nil
}
