package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"backend/graph/generated"
	"backend/graph/model"
	"backend/internal/gqlerr"
	"backend/internal/loader"
	"backend/internal/usecase"
	"context"

	"github.com/rotisserie/eris"
)

// Cardgroup is the resolver for the cardgroup field.
func (r *cardResolver) Cardgroup(ctx context.Context, obj *model.Card) (*model.Cardgroup, error) {
	loaders := loader.For(ctx)
	if loaders == nil {
		return nil, gqlerr.Internal(ctx, eris.New("loader: middleware not installed for /query"))
	}
	cg, err := loaders.Cardgroup.Load(ctx, obj.CardgroupID)()
	if err != nil {
		return nil, gqlerr.Internal(ctx, err)
	}
	return toCardgroupModel(cg), nil
}

// Owner is the resolver for the owner field.
func (r *cardgroupResolver) Owner(ctx context.Context, obj *model.Cardgroup) (*model.User, error) {
	loaders := loader.For(ctx)
	if loaders == nil {
		return nil, gqlerr.Internal(ctx, eris.New("loader: middleware not installed for /query"))
	}
	user, err := loaders.User.Load(ctx, obj.OwnerID)()
	if err != nil {
		return nil, gqlerr.Internal(ctx, err)
	}
	return toUserModel(user), nil
}

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, input model.UpdateProfileInput) (*model.UpdateProfilePayload, error) {
	user, err := r.User.UpdateUser(ctx, usecase.UpdateUserInput{
		DisplayName: input.DisplayName,
		Bio:         input.Bio,
	})
	if err != nil {
		return nil, err
	}
	return &model.UpdateProfilePayload{User: toUserModel(user)}, nil
}

// CreateCardgroup is the resolver for the createCardgroup field.
func (r *mutationResolver) CreateCardgroup(ctx context.Context, input model.NewCardgroupInput) (*model.CreateCardgroupPayload, error) {
	cg, err := r.CardgroupUC.Create(ctx, usecase.CreateCardgroupInput{Name: input.Name})
	if err != nil {
		return nil, err
	}
	return &model.CreateCardgroupPayload{Cardgroup: toCardgroupModel(cg)}, nil
}

// UpdateCardgroup is the resolver for the updateCardgroup field.
func (r *mutationResolver) UpdateCardgroup(ctx context.Context, id string, input model.UpdateCardgroupInput) (*model.UpdateCardgroupPayload, error) {
	cg, err := r.CardgroupUC.Update(ctx, id, usecase.UpdateCardgroupInput{Name: input.Name})
	if err != nil {
		return nil, err
	}
	return &model.UpdateCardgroupPayload{Cardgroup: toCardgroupModel(cg)}, nil
}

// DeleteCardgroup is the resolver for the deleteCardgroup field.
func (r *mutationResolver) DeleteCardgroup(ctx context.Context, id string) (bool, error) {
	if err := r.CardgroupUC.Delete(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// CreateCard is the resolver for the createCard field.
func (r *mutationResolver) CreateCard(ctx context.Context, input model.NewCardInput) (*model.CreateCardPayload, error) {
	card, err := r.CardUC.Create(ctx, usecase.CreateCardInput{
		CardgroupID: input.CardgroupID,
		Front:       input.Front,
		Back:        input.Back,
	})
	if err != nil {
		return nil, err
	}
	return &model.CreateCardPayload{Card: toCardModel(card)}, nil
}

// UpdateCard is the resolver for the updateCard field.
func (r *mutationResolver) UpdateCard(ctx context.Context, id string, input model.UpdateCardInput) (*model.UpdateCardPayload, error) {
	card, err := r.CardUC.Update(ctx, id, usecase.UpdateCardInput{
		Front: input.Front,
		Back:  input.Back,
	})
	if err != nil {
		return nil, err
	}
	return &model.UpdateCardPayload{Card: toCardModel(card)}, nil
}

// DeleteCard is the resolver for the deleteCard field.
func (r *mutationResolver) DeleteCard(ctx context.Context, id string) (bool, error) {
	if err := r.CardUC.Delete(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (string, error) {
	return "ok", nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	user, err := r.User.Me(ctx)
	if err != nil {
		return nil, err
	}
	return toUserModel(user), nil
}

// MyCardgroups is the resolver for the myCardgroups field.
func (r *queryResolver) MyCardgroups(ctx context.Context) ([]*model.Cardgroup, error) {
	cgs, err := r.CardgroupUC.MyCardgroups(ctx)
	if err != nil {
		return nil, err
	}
	return toCardgroupModels(cgs), nil
}

// Cardgroup is the resolver for the cardgroup field.
func (r *queryResolver) Cardgroup(ctx context.Context, id string) (*model.Cardgroup, error) {
	cg, err := r.CardgroupUC.Cardgroup(ctx, id)
	if err != nil {
		return nil, err
	}
	return toCardgroupModel(cg), nil
}

// Card is the resolver for the card field.
func (r *queryResolver) Card(ctx context.Context, id string) (*model.Card, error) {
	card, err := r.CardUC.Card(ctx, id)
	if err != nil {
		return nil, err
	}
	return toCardModel(card), nil
}

// CardsByCardgroup is the resolver for the cardsByCardgroup field.
func (r *queryResolver) CardsByCardgroup(ctx context.Context, cardgroupID string) ([]*model.Card, error) {
	cards, err := r.CardUC.CardsByCardgroup(ctx, cardgroupID)
	if err != nil {
		return nil, err
	}
	return toCardModels(cards), nil
}

// Card returns generated.CardResolver implementation.
func (r *Resolver) Card() generated.CardResolver { return &cardResolver{r} }

// Cardgroup returns generated.CardgroupResolver implementation.
func (r *Resolver) Cardgroup() generated.CardgroupResolver { return &cardgroupResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type cardResolver struct{ *Resolver }
type cardgroupResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
