package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"backend/graph/generated"
	"backend/graph/model"
	"backend/internal/auth"
	"backend/internal/domain"
	"backend/internal/gqlerr"
	"backend/internal/loader"
	"backend/internal/repository"
	"backend/internal/textdic"
	"backend/internal/usecase"
	"context"
	"encoding/base64"
	"errors"
	"time"

	"github.com/rotisserie/eris"
)

// Cardgroup is the resolver for the cardgroup field.
func (r *cardResolver) Cardgroup(ctx context.Context, obj *model.Card) (*model.Cardgroup, error) {
	loaders := loader.For(ctx)
	if loaders == nil {
		return nil, gqlerr.Internal(ctx, eris.New("loader: middleware not installed for /query"))
	}
	cg, err := loaders.Cardgroup.Load(ctx, obj.CardgroupID)()
	if err != nil {
		return nil, gqlerr.Internal(ctx, err)
	}
	return toCardgroupModel(cg), nil
}

// UserCardState is the resolver for the userCardState field.
func (r *cardResolver) UserCardState(ctx context.Context, obj *model.Card) (*model.UserCardState, error) {
	user := auth.UserFrom(ctx)
	if user == nil {
		return nil, gqlerr.Unauthenticated()
	}
	loaders := loader.For(ctx)
	if loaders == nil || loaders.UserCardFSRS == nil {
		return nil, gqlerr.Internal(ctx, eris.New("loader: user card fsrs loader not installed for /query"))
	}
	ucs, err := loaders.UserCardFSRS.Load(ctx, obj.ID)()
	if err != nil {
		return nil, gqlerr.Internal(ctx, err)
	}
	if ucs == nil {
		ucs = domain.NewUserCardFSRSForNewCard(user.Sub, obj.ID, obj.CreatedAt)
	}
	return toModelUserCardState(ucs), nil
}

// Owner is the resolver for the owner field.
func (r *cardgroupResolver) Owner(ctx context.Context, obj *model.Cardgroup) (*model.User, error) {
	loaders := loader.For(ctx)
	if loaders == nil {
		return nil, gqlerr.Internal(ctx, eris.New("loader: middleware not installed for /query"))
	}
	user, err := loaders.User.Load(ctx, obj.OwnerID)()
	if err != nil {
		return nil, gqlerr.Internal(ctx, err)
	}
	return toUserModel(user), nil
}

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, input model.UpdateProfileInput) (*model.UpdateProfilePayload, error) {
	user, err := r.UserUC.UpdateUser(ctx, usecase.UpdateUserInput{
		DisplayName: input.DisplayName,
		Bio:         input.Bio,
	})
	if err != nil {
		return nil, err
	}
	return &model.UpdateProfilePayload{User: toUserModel(user)}, nil
}

// CreateCardgroup is the resolver for the createCardgroup field.
func (r *mutationResolver) CreateCardgroup(ctx context.Context, input model.NewCardgroupInput) (*model.CreateCardgroupPayload, error) {
	cg, err := r.CardgroupUC.Create(ctx, usecase.CreateCardgroupInput{Name: input.Name})
	if err != nil {
		return nil, err
	}
	return &model.CreateCardgroupPayload{Cardgroup: toCardgroupModel(cg)}, nil
}

// UpdateCardgroup is the resolver for the updateCardgroup field.
func (r *mutationResolver) UpdateCardgroup(ctx context.Context, id string, input model.UpdateCardgroupInput) (*model.UpdateCardgroupPayload, error) {
	cg, err := r.CardgroupUC.Update(ctx, id, usecase.UpdateCardgroupInput{Name: input.Name})
	if err != nil {
		return nil, err
	}
	return &model.UpdateCardgroupPayload{Cardgroup: toCardgroupModel(cg)}, nil
}

// DeleteCardgroup is the resolver for the deleteCardgroup field.
func (r *mutationResolver) DeleteCardgroup(ctx context.Context, id string) (bool, error) {
	if err := r.CardgroupUC.Delete(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// CreateCard is the resolver for the createCard field.
//
// Returns a union: `model.CreateCardSuccess` on the happy path, or
// `model.CardDuplicateFrontError` when the (cardgroup_id, front) unique index
// is violated. The duplicate case is "errors as data" — the second return
// value is reserved for real errors (auth, validation, internal).
func (r *mutationResolver) CreateCard(ctx context.Context, input model.NewCardInput) (model.CreateCardResult, error) {
	outcome, err := r.CardUC.Create(ctx, usecase.CreateCardInput{
		CardgroupID: input.CardgroupID,
		Front:       input.Front,
		Back:        input.Back,
	})
	if err != nil {
		return nil, err
	}
	if outcome.Duplicate != nil {
		return model.CardDuplicateFrontError{
			Message:        "A card with this front already exists in this cardgroup",
			ExistingCardID: outcome.Duplicate.ExistingID,
			ExistingBack:   outcome.Duplicate.ExistingBack,
		}, nil
	}
	if outcome.Card == nil {
		return nil, gqlerr.Internal(ctx,
			eris.New("resolver: CreateCardOutcome has no variant set"))
	}
	return model.CreateCardSuccess{Card: toCardModel(outcome.Card)}, nil
}

// UpdateCard is the resolver for the updateCard field.
func (r *mutationResolver) UpdateCard(ctx context.Context, id string, input model.UpdateCardInput) (*model.UpdateCardPayload, error) {
	card, err := r.CardUC.Update(ctx, id, usecase.UpdateCardInput{
		Front: input.Front,
		Back:  input.Back,
	})
	if err != nil {
		return nil, err
	}
	return &model.UpdateCardPayload{Card: toCardModel(card)}, nil
}

// DeleteCard is the resolver for the deleteCard field.
func (r *mutationResolver) DeleteCard(ctx context.Context, id string) (bool, error) {
	if err := r.CardUC.Delete(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// DeleteCards is the resolver for the deleteCards field.
func (r *mutationResolver) DeleteCards(ctx context.Context, ids []string) (int, error) {
	n, err := r.CardUC.BulkDelete(ctx, ids)
	if err != nil {
		return 0, err
	}
	return int(n), nil
}

// HandleSwipe is the resolver for the handleSwipe field.
func (r *mutationResolver) HandleSwipe(ctx context.Context, input model.HandleSwipeInput) (*model.SwipeResponse, error) {
	out, err := r.SwipeUC.HandleSwipe(ctx, usecase.HandleSwipeInput{
		CardID:      input.CardID,
		CardgroupID: input.CardgroupID,
		Mode:        input.Mode,
	})
	if err != nil {
		return nil, err
	}
	return toSwipeResponseModel(ctx, out), nil
}

// UpsertDictionary is the resolver for the upsertDictionary field.
func (r *mutationResolver) UpsertDictionary(ctx context.Context, input model.UpsertDictionaryInput) (*model.UpsertDictionaryPayload, error) {
	out, err := r.DictionaryUC.Upsert(ctx, usecase.UpsertDictionaryInput{
		CardgroupID: input.CardgroupID,
		Payload:     input.Payload,
	})
	if err != nil {
		return nil, err
	}
	errs := make([]*model.DictionaryValidationError, 0, len(out.Errors))
	for _, e := range out.Errors {
		errs = append(errs, &model.DictionaryValidationError{
			Line:    e.Line,
			Message: e.Message,
			Kind:    dictionaryKindOrPanic(ctx, string(e.Kind)),
			Snippet: nilIfEmpty(e.Snippet),
			Front:   nilIfEmpty(e.Front),
			Back:    nilIfEmpty(e.Back),
		})
	}
	return &model.UpsertDictionaryPayload{
		Inserted: int(out.Inserted),
		Updated:  int(out.Updated),
		Errors:   errs,
	}, nil
}

// AdminUpdateUser is the resolver for the adminUpdateUser field.
func (r *mutationResolver) AdminUpdateUser(ctx context.Context, id string, input model.AdminUpdateUserInput) (*model.User, error) {
	user, err := r.AdminUserUC.Update(ctx, id, usecase.AdminUpdateUserInput{
		DisplayName: input.DisplayName,
		Bio:         input.Bio,
	})
	if err != nil {
		return nil, err
	}
	return toUserModel(user), nil
}

// AssignRole is the resolver for the assignRole field.
func (r *mutationResolver) AssignRole(ctx context.Context, userID string, roleID string) (*model.User, error) {
	user, err := r.AdminUserUC.AssignRole(ctx, userID, roleID)
	if err != nil {
		return nil, err
	}
	return toUserModel(user), nil
}

// RevokeRole is the resolver for the revokeRole field.
func (r *mutationResolver) RevokeRole(ctx context.Context, userID string, roleID string) (*model.User, error) {
	user, err := r.AdminUserUC.RevokeRole(ctx, userID, roleID)
	if err != nil {
		return nil, err
	}
	return toUserModel(user), nil
}

// CreateRole is the resolver for the createRole field.
func (r *mutationResolver) CreateRole(ctx context.Context, name string) (*model.Role, error) {
	role, err := r.AdminRoleUC.Create(ctx, name)
	if err != nil {
		return nil, err
	}
	return toRoleModel(role), nil
}

// UpdateRole is the resolver for the updateRole field.
func (r *mutationResolver) UpdateRole(ctx context.Context, id string, name string) (*model.Role, error) {
	role, err := r.AdminRoleUC.Update(ctx, id, name)
	if err != nil {
		return nil, err
	}
	return toRoleModel(role), nil
}

// DeleteRole is the resolver for the deleteRole field.
func (r *mutationResolver) DeleteRole(ctx context.Context, id string) (bool, error) {
	if err := r.AdminRoleUC.Delete(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// SetLastViewedCardgroup is the resolver for the setLastViewedCardgroup field.
func (r *mutationResolver) SetLastViewedCardgroup(ctx context.Context, cardgroupID string) (*model.User, error) {
	user, err := r.LastViewedCardgroupUC.Set(ctx, cardgroupID)
	if err != nil {
		return nil, err
	}
	return toUserModel(user), nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (string, error) {
	return "ok", nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	user, err := r.UserUC.Me(ctx)
	if err != nil {
		return nil, err
	}
	return toUserModel(user), nil
}

// Cardgroup is the resolver for the cardgroup field.
func (r *queryResolver) Cardgroup(ctx context.Context, id string) (*model.Cardgroup, error) {
	cg, err := r.CardgroupUC.Cardgroup(ctx, id)
	if err != nil {
		return nil, err
	}
	return toCardgroupModel(cg), nil
}

// MyCardgroupsConnection is the resolver for the myCardgroupsConnection field.
func (r *queryResolver) MyCardgroupsConnection(ctx context.Context, first *int, after *string, last *int, before *string, search *string, orderBy *model.CardgroupOrderBy, orderDirection *model.SortOrder) (*model.CardgroupConnection, error) {
	out, err := r.CardgroupUC.ListCardgroupsByOwnerConnection(ctx, usecase.CardgroupConnectionInput{
		First:          first,
		Last:           last,
		After:          after,
		Before:         before,
		Search:         search,
		OrderBy:        toUsecaseCardgroupOrderBy(orderBy),
		OrderDirection: toUsecaseSortOrder(orderDirection),
	})
	if err != nil {
		return nil, err
	}
	return toCardgroupConnectionModel(ctx, out), nil
}

// Card is the resolver for the card field.
func (r *queryResolver) Card(ctx context.Context, id string) (*model.Card, error) {
	card, err := r.CardUC.Card(ctx, id)
	if err != nil {
		return nil, err
	}
	return toCardModel(card), nil
}

// LearnNextDueCards is the resolver for the learnNextDueCards field.
func (r *queryResolver) LearnNextDueCards(ctx context.Context, cardgroupID string, limit *int) ([]*model.Card, error) {
	n := 0
	if limit != nil {
		n = *limit
	}
	cards, err := r.LearnUC.NextDueCards(ctx, cardgroupID, time.Now().UTC(), n)
	if err != nil {
		return nil, err
	}
	return toCardModels(ctx, cards), nil
}

// CardsByCardgroupConnection is the resolver for the cardsByCardgroupConnection field.
func (r *queryResolver) CardsByCardgroupConnection(ctx context.Context, cardgroupID string, first *int, after *string, last *int, before *string, search *string, orderBy *model.CardOrderBy, orderDirection *model.SortOrder) (*model.CardConnection, error) {
	out, err := r.CardUC.ListCardsByCardgroupConnection(ctx, usecase.CardConnectionInput{
		CardgroupID:    cardgroupID,
		First:          first,
		Last:           last,
		After:          after,
		Before:         before,
		Search:         search,
		OrderBy:        toUsecaseCardOrderBy(orderBy),
		OrderDirection: toUsecaseSortOrder(orderDirection),
	})
	if err != nil {
		return nil, err
	}
	return toCardConnectionModel(ctx, out), nil
}

// ValidateDictionary is the resolver for the validateDictionary field.
func (r *queryResolver) ValidateDictionary(ctx context.Context, input model.ValidateDictionaryInput) (*model.DictionaryValidationResult, error) {
	caller := auth.UserFrom(ctx)
	if caller == nil || caller.Sub == "" {
		return nil, gqlerr.Unauthenticated()
	}

	isAdmin, err := r.AuthSvc.IsAdmin(ctx, caller.Sub)
	if err != nil {
		if errors.Is(err, context.Canceled) || errors.Is(err, context.DeadlineExceeded) {
			return nil, gqlerr.Cancelled(ctx, err)
		}
		return nil, gqlerr.Internal(ctx, err)
	}
	if !isAdmin {
		return nil, gqlerr.NewForbidden("forbidden")
	}

	if input.Payload == "" {
		return nil, gqlerr.BadUserInput("payload", "payload must not be empty")
	}
	decoded, err := base64.StdEncoding.DecodeString(input.Payload)
	if err != nil {
		return nil, gqlerr.BadUserInput("payload", "payload must be standard base64-encoded text")
	}

	words, errs, perr := textdic.Process(string(decoded))
	if perr != nil {
		return nil, gqlerr.Internal(ctx, perr)
	}

	parsed := make([]*model.ParsedWord, 0, len(words))
	for _, w := range words {
		parsed = append(parsed, &model.ParsedWord{Front: w.Front, Back: w.Back, Line: w.Line})
	}
	validationErrs := make([]*model.DictionaryValidationError, 0, len(errs))
	for _, e := range errs {
		validationErrs = append(validationErrs, &model.DictionaryValidationError{
			Line:    e.Line,
			Message: e.Message,
			Kind:    dictionaryKindOrPanic(ctx, e.Kind.String()),
			Snippet: nilIfEmpty(e.Snippet),
		})
	}
	return &model.DictionaryValidationResult{
		Valid:       len(errs) == 0 && len(words) > 0,
		ParsedWords: parsed,
		Errors:      validationErrs,
	}, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, first *int, after *string, last *int, before *string, search *string) (*model.UserConnection, error) {
	uc, err := r.AdminUserUC.List(ctx, first, last, after, before, search)
	if err != nil {
		return nil, err
	}
	edges := make([]*model.UserEdge, len(uc.Edges))
	for i, e := range uc.Edges {
		edges[i] = &model.UserEdge{Cursor: e.Cursor, Node: toUserModel(e.Node)}
	}
	return &model.UserConnection{
		Edges: edges,
		PageInfo: &model.PageInfo{
			HasNextPage:     uc.PageInfo.HasNextPage,
			HasPreviousPage: uc.PageInfo.HasPreviousPage,
			StartCursor:     uc.PageInfo.StartCursor,
			EndCursor:       uc.PageInfo.EndCursor,
		},
		TotalCount: int(uc.TotalCount),
	}, nil
}

// AdminUser is the resolver for the adminUser field.
func (r *queryResolver) AdminUser(ctx context.Context, id string) (*model.User, error) {
	user, err := r.AdminUserUC.Get(ctx, id)
	if err != nil {
		return nil, err
	}
	if user == nil {
		return nil, nil
	}
	return toUserModel(user), nil
}

// Roles is the resolver for the roles field.
func (r *queryResolver) Roles(ctx context.Context) ([]*model.Role, error) {
	roles, err := r.AdminRoleUC.List(ctx)
	if err != nil {
		return nil, err
	}
	return toRoleModels(ctx, roles), nil
}

// Role is the resolver for the role field.
func (r *queryResolver) Role(ctx context.Context, id string) (*model.Role, error) {
	role, err := r.AdminRoleUC.Get(ctx, id)
	if err != nil {
		return nil, err
	}
	return toRoleModel(role), nil
}

// Roles is the resolver for the roles field.
func (r *userResolver) Roles(ctx context.Context, obj *model.User) ([]*model.Role, error) {
	caller := auth.UserFrom(ctx)
	if caller == nil || caller.Sub == "" {
		return nil, gqlerr.Unauthenticated()
	}
	if caller.Sub != obj.ID {
		if r.AuthSvc == nil {
			return nil, gqlerr.Internal(ctx, eris.New("resolver: user roles: AuthSvc not configured"))
		}
		isAdmin, err := r.AuthSvc.IsAdmin(ctx, caller.Sub)
		if err != nil {
			if errors.Is(err, context.Canceled) || errors.Is(err, context.DeadlineExceeded) {
				return nil, gqlerr.Cancelled(ctx, err)
			}
			return nil, gqlerr.Internal(ctx, eris.Wrap(err, "resolver: user roles: check admin"))
		}
		if !isAdmin {
			return nil, gqlerr.NewForbidden("admin only")
		}
	}

	loaders := loader.For(ctx)
	if loaders == nil {
		return nil, gqlerr.Internal(ctx, eris.New("loader: middleware not installed for /query"))
	}
	roles, err := loaders.RoleByUserID.Load(ctx, obj.ID)()
	if err != nil {
		if errors.Is(err, context.Canceled) || errors.Is(err, context.DeadlineExceeded) {
			return nil, gqlerr.Cancelled(ctx, err)
		}
		return nil, gqlerr.Internal(ctx, eris.Wrap(err, "resolver: user roles"))
	}
	return toRoleModels(ctx, roles), nil
}

// LastViewedCardgroup is the resolver for the lastViewedCardgroup field.
func (r *userResolver) LastViewedCardgroup(ctx context.Context, obj *model.User) (*model.Cardgroup, error) {
	if obj.LastViewedCardgroup == nil || obj.LastViewedCardgroup.ID == "" {
		return nil, nil
	}
	loaders := loader.For(ctx)
	if loaders == nil {
		return nil, gqlerr.Internal(ctx, eris.New("loader: middleware not installed for /query"))
	}
	cg, err := loaders.Cardgroup.Load(ctx, obj.LastViewedCardgroup.ID)()
	if err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return nil, nil
		}
		if errors.Is(err, context.Canceled) || errors.Is(err, context.DeadlineExceeded) {
			return nil, gqlerr.Cancelled(ctx, err)
		}
		return nil, gqlerr.Internal(ctx, eris.Wrap(err, "resolver: user last viewed cardgroup"))
	}
	return toCardgroupModel(cg), nil
}

// Card returns generated.CardResolver implementation.
func (r *Resolver) Card() generated.CardResolver { return &cardResolver{r} }

// Cardgroup returns generated.CardgroupResolver implementation.
func (r *Resolver) Cardgroup() generated.CardgroupResolver { return &cardgroupResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type cardResolver struct{ *Resolver }
type cardgroupResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
