package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"backend/graph/model"
	"backend/internal/gqlerr"
	"context"
)

// MyLearningStats is the resolver for the myLearningStats field.
func (r *queryResolver) MyLearningStats(ctx context.Context) (*model.LearningStats, error) {
	res, err := r.StatsUC.MyLearningStats(ctx)
	if err != nil {
		return nil, gqlerr.FromUsecaseError(ctx, err)
	}
	return toLearningStatsModel(ctx, res)
}
