package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.91

import (
	"backend/graph/model"
	"backend/internal/gqlerr"
	"backend/internal/usecase"
	"context"

	"github.com/rotisserie/eris"
)

// HandleSwipe is the resolver for the handleSwipe field.
//
// Returns a union: `model.HandleSwipeSuccess` on the happy path, or
// `model.InputValidationError` when the mode, cardId, or cardgroupId fails
// validation. Validation failures are "errors as data" — the error return is
// reserved for auth and infrastructure failures.
func (r *mutationResolver) HandleSwipe(ctx context.Context, input model.HandleSwipeInput) (model.HandleSwipeResult, error) {
	outcome, err := r.SwipeUC.HandleSwipe(ctx, usecase.HandleSwipeInput{
		CardID:      input.CardID,
		CardgroupID: input.CardgroupID,
		Mode:        input.Mode,
	})
	if err != nil {
		return nil, gqlerr.FromUsecaseError(ctx, err)
	}
	if outcome.Validation != nil {
		return model.InputValidationError{
			Field:   outcome.Validation.Field,
			Message: outcome.Validation.Message,
		}, nil
	}
	if outcome.Swipe == nil {
		return nil, gqlerr.Internal(ctx,
			eris.New("resolver: HandleSwipeOutcome has no variant set"))
	}
	return model.HandleSwipeSuccess{Response: toSwipeResponseModel(outcome.Swipe)}, nil
}
