package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"backend/graph/generated"
	"backend/graph/model"
	"backend/internal/gqlerr"
	"backend/internal/usecase"
	"context"

	"github.com/rotisserie/eris"
)

// UpdateProfile is the resolver for the updateProfile field.
//
// Returns a union: `model.UpdateProfileSuccess` on the happy path, or
// `model.InputValidationError` when displayName or bio fails validation.
// Validation failures are "errors as data" — the error return is reserved
// for auth and infrastructure failures.
func (r *mutationResolver) UpdateProfile(ctx context.Context, input model.UpdateProfileInput) (model.UpdateProfileResult, error) {
	outcome, err := r.UserUC.UpdateUser(ctx, usecase.UpdateUserInput{
		DisplayName: input.DisplayName,
		Bio:         input.Bio,
	})
	if err != nil {
		return nil, gqlerr.FromUsecaseError(ctx, err)
	}
	if outcome.Validation != nil {
		return toInputValidationError(outcome.Validation), nil
	}
	if outcome.User == nil {
		return nil, gqlerr.Internal(ctx,
			eris.New("resolver: UpdateProfileOutcome has no variant set"))
	}
	return model.UpdateProfileSuccess{User: toUserModel(outcome.User)}, nil
}

// DeleteMyAccount is the resolver for the deleteMyAccount field.
func (r *mutationResolver) DeleteMyAccount(ctx context.Context) (bool, error) {
	if err := r.UserUC.DeleteMyAccount(ctx); err != nil {
		return false, gqlerr.FromUsecaseError(ctx, err)
	}
	return true, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	user, err := r.UserUC.Me(ctx)
	if err != nil {
		return nil, gqlerr.FromUsecaseError(ctx, err)
	}
	return toUserModel(user), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type mutationResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
