// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
	"time"
)

// Result of `adminEditUser`. Either the updated user, an input-validation
// failure, a CannotRevokeOwnAdminRoleError when the caller tries to demote
// themselves, or a ConcurrentUpdateError when the submitted version is stale.
type AdminEditUserResult interface {
	IsAdminEditUserResult()
}

// Result of `createCard`. Either the created card, or a typed duplicate-front error returned as data.
type CreateCardResult interface {
	IsCreateCardResult()
}

// Result of `createCardgroup`. Either the created cardgroup or an input-validation failure.
type CreateCardgroupResult interface {
	IsCreateCardgroupResult()
}

// Result of `createRole`. Either the new role or an input-validation failure.
type CreateRoleResult interface {
	IsCreateRoleResult()
}

// Result of `handleSwipe`. Either the swipe response or an input-validation failure.
type HandleSwipeResult interface {
	IsHandleSwipeResult()
}

// Result of `setLastViewedCardgroup`. Either the updated user or an input-validation failure.
type SetLastViewedCardgroupResult interface {
	IsSetLastViewedCardgroupResult()
}

// Result of `updateCard`. Either the updated card or an input-validation failure.
type UpdateCardResult interface {
	IsUpdateCardResult()
}

// Result of `updateCardgroup`. Either the updated cardgroup or an input-validation failure.
type UpdateCardgroupResult interface {
	IsUpdateCardgroupResult()
}

// Result of `updateProfile`. Either the updated user or an input-validation failure.
type UpdateProfileResult interface {
	IsUpdateProfileResult()
}

// Result of `updateRole`. Either the updated role, or a typed
// CannotModifySystemRoleError describing the system-role guard.
type UpdateRoleResult interface {
	IsUpdateRoleResult()
}

// Interface for typed business errors surfaced as `data` (Apollo "Errors as data"
// pattern). Implementors expose a `message: String!` and may add typed fields.
type UserError interface {
	IsUserError()
	GetMessage() string
}

// Input for atomically editing admin-managed user fields and final roles.
type AdminEditUserInput struct {
	// Current `User.version` observed by the client; stale values return `ConcurrentUpdateError`.
	ExpectedVersion int `json:"expectedVersion"`
	// null/omitted = unchanged. Non-null = set; must be 1-50 grapheme clusters after trim. Empty string is rejected with BAD_USER_INPUT.
	DisplayName *string `json:"displayName,omitempty"`
	// null/omitted = unchanged. Empty string clears the field. Non-empty must be <= 500 grapheme clusters.
	Bio *string `json:"bio,omitempty"`
	// Declarative final role set. Empty list removes all roles unless self-demotion guard blocks it.
	RoleIds []string `json:"roleIds"`
}

// Returned by `adminEditUser` when the admin's profile and role edit succeeded.
// Carries the updated `user` so clients can refresh the profile and role view
// without a follow-up query.
type AdminEditUserSuccess struct {
	User *User `json:"user"`
}

func (AdminEditUserSuccess) IsAdminEditUserResult() {}

// Returned by `updateRole` when the target role is a system role
// ("admin", "general"). System roles are immutable by domain invariant — the
// backend refuses the rename regardless of caller privilege.
//
// The variant carries the offending role's identity so the client can render
// "system role 'admin' cannot be renamed" without re-fetching.
type CannotModifySystemRoleError struct {
	Message  string `json:"message"`
	RoleID   string `json:"roleId"`
	RoleName string `json:"roleName"`
}

func (CannotModifySystemRoleError) IsUserError()            {}
func (this CannotModifySystemRoleError) GetMessage() string { return this.Message }

func (CannotModifySystemRoleError) IsUpdateRoleResult() {}

// Typed business error returned by `adminEditUser` when the caller attempts to
// remove the admin role from their own account. Self-demotion is rejected by the
// server regardless of caller privilege.
type CannotRevokeOwnAdminRoleError struct {
	Message string `json:"message"`
}

func (CannotRevokeOwnAdminRoleError) IsUserError()            {}
func (this CannotRevokeOwnAdminRoleError) GetMessage() string { return this.Message }

func (CannotRevokeOwnAdminRoleError) IsAdminEditUserResult() {}

// A flashcard with viewer-specific FSRS scheduling state.
type Card struct {
	ID    string `json:"id"`
	Front string `json:"front"`
	Back  string `json:"back"`
	// Foreign key to the owning cardgroup. The `cardgroup` prefix names the related type, not a stutter of the parent type.
	CardgroupID string `json:"cardgroupId"`
	// The parent cardgroup. Resolved via the per-request Cardgroup DataLoader.
	Cardgroup *Cardgroup `json:"cardgroup"`
	// Viewer's per-user FSRS state. For cards the viewer has not reviewed,
	// resolves to a synthesized new-card state.
	UserCardState *UserCardState `json:"userCardState"`
	CreatedAt     time.Time      `json:"createdAt"`
	UpdatedAt     time.Time      `json:"updatedAt"`
}

// Paginated list of Cards (Relay Connection).
type CardConnection struct {
	Edges    []*CardEdge `json:"edges"`
	PageInfo *PageInfo   `json:"pageInfo"`
	// Total cards in the cardgroup, regardless of page window.
	// Backed by a separate COUNT(*); intended for cardgroups up to ~10k cards.
	TotalCount int `json:"totalCount"`
}

// Typed business error returned by `createCard` when an existing card in the same cardgroup already has the same front.
type CardDuplicateFrontError struct {
	Message        string `json:"message"`
	ExistingCardID string `json:"existingCardId"`
	ExistingBack   string `json:"existingBack"`
}

func (CardDuplicateFrontError) IsUserError()            {}
func (this CardDuplicateFrontError) GetMessage() string { return this.Message }

func (CardDuplicateFrontError) IsCreateCardResult() {}

// One element in a CardConnection.
type CardEdge struct {
	// Opaque cursor for this position. Currently equal to node.id.
	Cursor string `json:"cursor"`
	Node   *Card  `json:"node"`
}

// A user-owned named collection of flashcards. Owns no Card aggregate; cards live in a sibling aggregate.
type Cardgroup struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	OwnerID   string    `json:"ownerId"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	// The owning user. Resolved via the per-request User DataLoader.
	Owner *User `json:"owner"`
}

// A page of cardgroups returned from a paginated query.
type CardgroupConnection struct {
	Edges    []*CardgroupEdge `json:"edges"`
	PageInfo *PageInfo        `json:"pageInfo"`
	// Total cardgroup count matching the filter (independent of paging).
	TotalCount int `json:"totalCount"`
}

// One cardgroup plus the cursor pointing at it.
type CardgroupEdge struct {
	// Opaque cursor for resuming pagination at this edge. Currently the cardgroup id.
	Cursor string     `json:"cursor"`
	Node   *Cardgroup `json:"node"`
}

// Returned by `adminEditUser` when the submitted expected version does not
// match the target user's current optimistic-concurrency token.
type ConcurrentUpdateError struct {
	Message string `json:"message"`
}

func (ConcurrentUpdateError) IsUserError()            {}
func (this ConcurrentUpdateError) GetMessage() string { return this.Message }

func (ConcurrentUpdateError) IsAdminEditUserResult() {}

// Success result of `createCard`. Returned as the union variant when the card was created.
type CreateCardSuccess struct {
	Card *Card `json:"card"`
}

func (CreateCardSuccess) IsCreateCardResult() {}

// Success variant returned by `createCardgroup` when the cardgroup was created. Carries the new `cardgroup` so clients can insert it into local caches without a follow-up query.
type CreateCardgroupSuccess struct {
	Cardgroup *Cardgroup `json:"cardgroup"`
}

func (CreateCardgroupSuccess) IsCreateCardgroupResult() {}

// Returned by `createRole` when a new role was successfully created. Carries
// the freshly inserted `role` so clients can insert it into local caches
// without a follow-up query.
type CreateRoleSuccess struct {
	Role *Role `json:"role"`
}

func (CreateRoleSuccess) IsCreateRoleResult() {}

// Per-line parse failure surfaced by `validateDictionary` / `upsertDictionary`. Branch on `kind` rather than substring-matching `message`.
type DictionaryValidationError struct {
	// 1-based line number where the error was detected, or 0 when the error applies to the payload as a whole (e.g. oversized or empty payload).
	Line int `json:"line"`
	// Human-readable, English error message.
	Message string `json:"message"`
	// Closed classifier for the parse event.
	Kind DictionaryValidationKind `json:"kind"`
	// Parser-extracted snippet. Populated for FRONT_ONLY (the WORD token text), BACK_ONLY (the DEFINITION token text), and UNRECOGNIZED (the recovered malformed line). Null for HARD and DUPLICATE.
	Snippet *string `json:"snippet,omitempty"`
	// Dedupe-duplicate only: the front term of the dropped row. Null for every other kind.
	Front *string `json:"front,omitempty"`
	// Dedupe-duplicate only: the back text of the dropped row. Null for every other kind.
	Back *string `json:"back,omitempty"`
}

func (DictionaryValidationError) IsUserError()            {}
func (this DictionaryValidationError) GetMessage() string { return this.Message }

// Result of validating a dictionary payload. The resolver enforces the
// invariant valid = (len(errors) == 0 && len(parsedWords) > 0); conflicting
// states are representable but never emitted.
type DictionaryValidationResult struct {
	// True iff the payload parsed without any errors and produced at least one word.
	Valid bool `json:"valid"`
	// Parsed words preserving source order.
	ParsedWords []*ParsedWord `json:"parsedWords"`
	// Structured per-line errors, empty when valid is true.
	Errors []*DictionaryValidationError `json:"errors"`
}

// Input for `handleSwipe`. Identifies the card under review and the rating the user emitted.
type HandleSwipeInput struct {
	CardID      string `json:"cardId"`
	CardgroupID string `json:"cardgroupId"`
	// 1=Again, 2=Hard, 4=Easy. The 3-step UI does not emit 3=Good.
	Mode int `json:"mode"`
}

// Success variant returned by `handleSwipe` when the swipe was recorded. Carries the latest `SwipeResponse` (performance snapshot only — the client manages its own queue and prefetches the next page separately).
type HandleSwipeSuccess struct {
	Response *SwipeResponse `json:"response"`
}

func (HandleSwipeSuccess) IsHandleSwipeResult() {}

// Generic input-validation failure used as the UserError variant in outcome-union
// mutations. Mapped from `*ucerr.ValidationError` via `gqlerr.FromUsecaseError`.
// Also surfaced via the `errors` array with `extensions.code = "BAD_USER_INPUT"`
// and `extensions.field` for mutations that have not yet been promoted to a
// result union.
type InputValidationError struct {
	// The input field that failed validation. Matches the GraphQL input field name (camelCase).
	Field string `json:"field"`
	// Human-readable, English error message.
	Message string `json:"message"`
}

func (InputValidationError) IsAdminEditUserResult() {}

func (InputValidationError) IsCreateRoleResult() {}

func (InputValidationError) IsUpdateCardResult() {}

func (InputValidationError) IsCreateCardgroupResult() {}

func (InputValidationError) IsUpdateCardgroupResult() {}

func (InputValidationError) IsSetLastViewedCardgroupResult() {}

func (InputValidationError) IsUserError()            {}
func (this InputValidationError) GetMessage() string { return this.Message }

func (InputValidationError) IsHandleSwipeResult() {}

func (InputValidationError) IsUpdateProfileResult() {}

// Root of all write operations exposed by the GraphQL API. See per-field doc-blocks for individual mutations.
type Mutation struct {
}

// Input for creating a new card.
type NewCardInput struct {
	CardgroupID string `json:"cardgroupId"`
	// 1-500 grapheme clusters (length measured after trimming surrounding whitespace).
	Front string `json:"front"`
	// 1-500 grapheme clusters (length measured after trimming surrounding whitespace).
	Back string `json:"back"`
}

// Input for `createCardgroup`.
type NewCardgroupInput struct {
	// 1-100 grapheme clusters (length measured after trimming surrounding whitespace).
	Name string `json:"name"`
}

// Relay PageInfo describing whether more pages exist on either side and the boundary cursors.
type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

// Single parsed dictionary entry.
type ParsedWord struct {
	// Front (term) text.
	Front string `json:"front"`
	// Back (definition) text.
	Back string `json:"back"`
	// 1-based line number in the decoded payload where this entry was parsed.
	Line int `json:"line"`
}

// Per-viewer performance metrics returned alongside a swipe response.
type PerformanceMetrics struct {
	SuccessRate   float64 `json:"successRate"`
	AvgDifficulty float64 `json:"avgDifficulty"`
	RetentionRate float64 `json:"retentionRate"`
	StudyStreak   int     `json:"studyStreak"`
	LapseRate     float64 `json:"lapseRate"`
	ReviewCount   int     `json:"reviewCount"`
}

// Root of all read operations exposed by the GraphQL API. See per-field doc-blocks for individual queries.
type Query struct {
}

// A named permission role. Names are stored lowercase (e.g., "admin", "general").
type Role struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

// Success variant returned by `setLastViewedCardgroup` when the preference was recorded. Carries the updated `user` so clients can refresh the last-viewed state without a follow-up query.
type SetLastViewedCardgroupSuccess struct {
	User *User `json:"user"`
}

func (SetLastViewedCardgroupSuccess) IsSetLastViewedCardgroupResult() {}

// Response returned by `handleSwipe` — the latest performance snapshot for the swipe flow.
type SwipeResponse struct {
	// Performance mode for the swipe flow, expressed as an Int in the 0..4 range.
	PerformanceMode int                 `json:"performanceMode"`
	Metrics         *PerformanceMetrics `json:"metrics"`
}

// Input for `updateCard`. Fields default to "leave unchanged" when null or omitted.
type UpdateCardInput struct {
	// null or omitted = leave unchanged.
	Front *string `json:"front,omitempty"`
	// null or omitted = leave unchanged.
	Back *string `json:"back,omitempty"`
}

// Success variant returned by `updateCard` when the card was updated. Carries the updated `card` so clients can refresh local state without a follow-up query.
type UpdateCardSuccess struct {
	Card *Card `json:"card"`
}

func (UpdateCardSuccess) IsUpdateCardResult() {}

// Input for `updateCardgroup`. Fields default to "leave unchanged" when null or omitted.
type UpdateCardgroupInput struct {
	// null or omitted = leave unchanged.
	Name *string `json:"name,omitempty"`
}

// Success variant returned by `updateCardgroup` when the cardgroup was updated. Carries the updated `cardgroup` so clients can refresh local state without a follow-up query.
type UpdateCardgroupSuccess struct {
	Cardgroup *Cardgroup `json:"cardgroup"`
}

func (UpdateCardgroupSuccess) IsUpdateCardgroupResult() {}

// Input for `updateProfile`. The authenticated caller's own profile fields.
type UpdateProfileInput struct {
	// 1-50 characters (length measured after trimming surrounding whitespace).
	DisplayName string `json:"displayName"`
	// null or omitted = leave unchanged; empty string = explicit clear.
	Bio *string `json:"bio,omitempty"`
}

// Success variant returned by `updateProfile` when the profile was updated. Carries the updated `user` so clients can refresh local state without a follow-up query.
type UpdateProfileSuccess struct {
	User *User `json:"user"`
}

func (UpdateProfileSuccess) IsUpdateProfileResult() {}

// Success result of `updateRole`. Returned when the role rename succeeded.
type UpdateRoleSuccess struct {
	Role *Role `json:"role"`
}

func (UpdateRoleSuccess) IsUpdateRoleResult() {}

// Input for upserting a parsed dictionary into a target cardgroup.
// `UpsertDictionaryInput` reuses the same base64 + tab/space-separated front/back format as `validateDictionary`.
type UpsertDictionaryInput struct {
	// Target cardgroup ID. Must reference an existing cardgroup (FK constraint at upsert time). FORBIDDEN response is enforced at the mutation level for non-admin callers.
	CardgroupID string `json:"cardgroupId"`
	// Base64-encoded payload (standard alphabet, with padding). Same format as validateDictionary.
	Payload string `json:"payload"`
}

// Result of an `upsertDictionary` call. `inserted + updated` is the number of rows that were processed successfully.
// `errors` carries per-line parse failures; the upsert proceeds with the valid rows when errors are non-empty.
type UpsertDictionaryPayload struct {
	// Number of cards newly inserted.
	Inserted int `json:"inserted"`
	// Number of cards updated (back text changed via ON CONFLICT).
	Updated int `json:"updated"`
	// Per-line parse errors. Empty when the entire payload parsed cleanly.
	Errors []*DictionaryValidationError `json:"errors"`
}

// Authenticated user's profile. 1:1 with auth.users.
type User struct {
	// Matches auth.users.id (UUID v4).
	ID string `json:"id"`
	// Optimistic-concurrency token; pass as `AdminEditUserInput.expectedVersion`. A mismatch yields `ConcurrentUpdateError`.
	Version     int     `json:"version"`
	DisplayName *string `json:"displayName,omitempty"`
	Bio         *string `json:"bio,omitempty"`
	AvatarURL   *string `json:"avatarUrl,omitempty"`
	// Roles assigned to this user. Resolved via the per-request RoleByUserID DataLoader.
	Roles []*Role `json:"roles"`
	// The cardgroup this user most recently viewed on /learn.
	// Used to land returning users directly on the learn screen.
	// Null when never set, or when the referenced cardgroup was deleted (FK cascade SET NULL).
	LastViewedCardgroup *Cardgroup `json:"lastViewedCardgroup,omitempty"`
}

// Per-user FSRS scheduling state for a single card.
type UserCardState struct {
	Due           time.Time `json:"due"`
	Stability     float64   `json:"stability"`
	Difficulty    float64   `json:"difficulty"`
	State         int       `json:"state"`
	Reps          int       `json:"reps"`
	Lapses        int       `json:"lapses"`
	LastReview    time.Time `json:"lastReview"`
	ElapsedDays   int       `json:"elapsedDays"`
	ScheduledDays int       `json:"scheduledDays"`
}

// Paginated list of Users (Relay Connection).
type UserConnection struct {
	Edges    []*UserEdge `json:"edges"`
	PageInfo *PageInfo   `json:"pageInfo"`
	// Total users matching the filter, regardless of page window.
	TotalCount int `json:"totalCount"`
}

// One element in a UserConnection.
type UserEdge struct {
	// Opaque cursor for this position. Currently equal to node.id.
	Cursor string `json:"cursor"`
	Node   *User  `json:"node"`
}

// Base64-encoded dictionary text payload submitted for validation.
type ValidateDictionaryInput struct {
	// Base64-encoded text payload (standard alphabet, with padding). One front/back pair per line.
	Payload string `json:"payload"`
}

// Field to order Cards by in paginated queries. DUE uses the viewer's due state.
type CardOrderBy string

const (
	CardOrderByID        CardOrderBy = "ID"
	CardOrderByCreatedAt CardOrderBy = "CREATED_AT"
	CardOrderByUpdatedAt CardOrderBy = "UPDATED_AT"
	CardOrderByDue       CardOrderBy = "DUE"
)

var AllCardOrderBy = []CardOrderBy{
	CardOrderByID,
	CardOrderByCreatedAt,
	CardOrderByUpdatedAt,
	CardOrderByDue,
}

func (e CardOrderBy) IsValid() bool {
	switch e {
	case CardOrderByID, CardOrderByCreatedAt, CardOrderByUpdatedAt, CardOrderByDue:
		return true
	}
	return false
}

func (e CardOrderBy) String() string {
	return string(e)
}

func (e *CardOrderBy) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CardOrderBy(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CardOrderBy", str)
	}
	return nil
}

func (e CardOrderBy) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

// Field to order Cardgroups by in paginated queries.
type CardgroupOrderBy string

const (
	CardgroupOrderByID        CardgroupOrderBy = "ID"
	CardgroupOrderByCreatedAt CardgroupOrderBy = "CREATED_AT"
	CardgroupOrderByUpdatedAt CardgroupOrderBy = "UPDATED_AT"
	CardgroupOrderByName      CardgroupOrderBy = "NAME"
)

var AllCardgroupOrderBy = []CardgroupOrderBy{
	CardgroupOrderByID,
	CardgroupOrderByCreatedAt,
	CardgroupOrderByUpdatedAt,
	CardgroupOrderByName,
}

func (e CardgroupOrderBy) IsValid() bool {
	switch e {
	case CardgroupOrderByID, CardgroupOrderByCreatedAt, CardgroupOrderByUpdatedAt, CardgroupOrderByName:
		return true
	}
	return false
}

func (e CardgroupOrderBy) String() string {
	return string(e)
}

func (e *CardgroupOrderBy) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CardgroupOrderBy(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CardgroupOrderBy", str)
	}
	return nil
}

func (e CardgroupOrderBy) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

// Classifier for a DictionaryValidationError. Closed enumeration; branch on this rather than substring-matching `message`.
type DictionaryValidationKind string

const (
	// Programming-error sentinel. Never returned by a healthy server. If a client observes this, file a bug — the server should be panicking or asserting before this value escapes.
	DictionaryValidationKindUnknown DictionaryValidationKind = "UNKNOWN"
	// Hard error: payload-level (oversized / empty) or grammar/lexer error not recovered by skip productions.
	DictionaryValidationKindHard DictionaryValidationKind = "HARD"
	// Skipped: a lone WORD line with no DEFINITION attached. The dropped front term is in `snippet`.
	DictionaryValidationKindFrontOnly DictionaryValidationKind = "FRONT_ONLY"
	// Skipped: a lone DEFINITION line with no preceding front. The dropped back text is in `snippet`.
	DictionaryValidationKindBackOnly DictionaryValidationKind = "BACK_ONLY"
	// Skipped: an unrecognized character was encountered. The recovered line content is in `snippet`.
	DictionaryValidationKindUnrecognized DictionaryValidationKind = "UNRECOGNIZED"
	// Post-parse dedupe: a duplicate row was dropped. The dropped row's `front` and `back` are populated.
	DictionaryValidationKindDuplicate DictionaryValidationKind = "DUPLICATE"
)

var AllDictionaryValidationKind = []DictionaryValidationKind{
	DictionaryValidationKindUnknown,
	DictionaryValidationKindHard,
	DictionaryValidationKindFrontOnly,
	DictionaryValidationKindBackOnly,
	DictionaryValidationKindUnrecognized,
	DictionaryValidationKindDuplicate,
}

func (e DictionaryValidationKind) IsValid() bool {
	switch e {
	case DictionaryValidationKindUnknown, DictionaryValidationKindHard, DictionaryValidationKindFrontOnly, DictionaryValidationKindBackOnly, DictionaryValidationKindUnrecognized, DictionaryValidationKindDuplicate:
		return true
	}
	return false
}

func (e DictionaryValidationKind) String() string {
	return string(e)
}

func (e *DictionaryValidationKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DictionaryValidationKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DictionaryValidationKind", str)
	}
	return nil
}

func (e DictionaryValidationKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

// Sort order for paginated queries.
type SortOrder string

const (
	SortOrderAsc  SortOrder = "ASC"
	SortOrderDesc SortOrder = "DESC"
)

var AllSortOrder = []SortOrder{
	SortOrderAsc,
	SortOrderDesc,
}

func (e SortOrder) IsValid() bool {
	switch e {
	case SortOrderAsc, SortOrderDesc:
		return true
	}
	return false
}

func (e SortOrder) String() string {
	return string(e)
}

func (e *SortOrder) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortOrder(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortOrder", str)
	}
	return nil
}

func (e SortOrder) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
