name: flamingo-armond frontend CI

on:
  push:
    branches:
      - master
    paths:
      - 'frontend/**'      

jobs:
  frontend:
    runs-on: ubuntu-22.04
    environment: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.13.1'
      - name: Install pnpm
        run: npm install -g pnpm
        working-directory: ./frontend
      - name: Clean install
        run: pnpm install --frozen-lockfile
        working-directory: ./frontend
      - name: Test
        run: pnpm run test
        working-directory: ./frontend
